/* Gate 5.2C canonical screen/state + policy registry - full /api/v1/ paths, corrected Today discriminators, care journeys enabled. */
(function () {
  window.GATE52C_SCREENS = [
  {
    "id": "G5-AUTH-01",
    "flow": "AUTH",
    "titleFa": "ورود با شماره موبایل",
    "titleEn": "Mobile entry",
    "route": "/auth/mobile",
    "kind": "entry",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "requestOtp",
    "backendOp": "POST /api/v1/auth/otp/request",
    "blocking": true,
    "source": "openapi.json",
    "next": "G5-AUTH-02"
  },
  {
    "id": "G5-AUTH-02",
    "flow": "AUTH",
    "titleFa": "درخواست ارسال کد",
    "titleEn": "OTP request sent",
    "route": "/auth/otp",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "requestOtp",
    "backendOp": "POST /api/v1/auth/otp/request",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-AUTH-03"
  },
  {
    "id": "G5-AUTH-03",
    "flow": "AUTH",
    "titleFa": "شمارش معکوس و ارسال مجدد",
    "titleEn": "OTP countdown/resend",
    "route": "/auth/otp",
    "kind": "otp",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "requestOtp (resend)",
    "backendOp": "POST /api/v1/auth/otp/request",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-AUTH-04"
  },
  {
    "id": "G5-AUTH-04",
    "flow": "AUTH",
    "titleFa": "تأیید کد (در حال بررسی)",
    "titleEn": "OTP verifying",
    "route": "/auth/otp",
    "kind": "otp",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify",
    "blocking": true,
    "source": "openapi.json",
    "next": "G5-ONB-01",
    "branches": [
      "G5-AUTH-05",
      "G5-AUTH-06",
      "G5-AUTH-07",
      "G5-AUTH-08"
    ]
  },
  {
    "id": "G5-AUTH-05",
    "flow": "AUTH",
    "titleFa": "کد نامعتبر",
    "titleEn": "invalid",
    "route": "/auth/otp",
    "kind": "otp",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify → invalid",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-03"
  },
  {
    "id": "G5-AUTH-06",
    "flow": "AUTH",
    "titleFa": "کد منقضی‌شده",
    "titleEn": "expired",
    "route": "/auth/otp",
    "kind": "otp",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify → expired",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-03"
  },
  {
    "id": "G5-AUTH-07",
    "flow": "AUTH",
    "titleFa": "کد قبلاً استفاده‌شده",
    "titleEn": "consumed",
    "route": "/auth/otp",
    "kind": "otp",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify → consumed",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-03"
  },
  {
    "id": "G5-AUTH-08",
    "flow": "AUTH",
    "titleFa": "کد یافت نشد",
    "titleEn": "not_found",
    "route": "/auth/otp",
    "kind": "otp",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify → not_found",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-AUTH-09",
    "flow": "AUTH",
    "titleFa": "قفل‌شده — تلاش بیش از حد",
    "titleEn": "locked",
    "route": "/auth/locked",
    "kind": "lock",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "verifyOtp",
    "backendOp": "POST /api/v1/auth/otp/verify → locked",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-AUTH-10",
    "flow": "AUTH",
    "titleFa": "محدودیت نرخ درخواست (۴۲۹)",
    "titleEn": "rate limited, distinct from lock",
    "route": "/auth/mobile",
    "kind": "lock",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "requestOtp",
    "backendOp": "POST /api/v1/auth/otp/request → 429",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-AUTH-11",
    "flow": "AUTH",
    "titleFa": "خطا در ارسال پیامک",
    "titleEn": "OTP delivery failure",
    "route": "/auth/otp",
    "kind": "error-block",
    "tone": "error",
    "k8": "gap",
    "k9": "K9.0",
    "disposition": "gated",
    "command": "requestOtp",
    "backendOp": "Payamak Panel (no delivery-status callback)",
    "blocking": true,
    "source": "assumed",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-AUTH-12",
    "flow": "AUTH",
    "titleFa": "پایان نشست",
    "titleEn": "session expired",
    "route": "/auth/session-expired",
    "kind": "error-block",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "refreshSession",
    "backendOp": "POST /api/v1/auth/session/refresh",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-AUTH-13",
    "flow": "AUTH",
    "titleFa": "بازیابی خودکار نشست",
    "titleEn": "automatic session recovery",
    "route": "/onboarding/bootstrap",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "refreshSession",
    "backendOp": "POST /api/v1/auth/session/refresh",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ONB-06"
  },
  {
    "id": "G5-AUTH-14",
    "flow": "AUTH",
    "titleFa": "تأیید خروج از حساب",
    "titleEn": "logout confirmation",
    "route": "/account",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "logout",
    "backendOp": "POST /api/v1/auth/session/logout",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-AUTH-01"
  },
  {
    "id": "G5-ONB-01",
    "flow": "ONB",
    "titleFa": "ایجاد خانوار (نام الزامی)",
    "titleEn": "household creation, name required",
    "route": "/onboarding/household",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createHousehold",
    "backendOp": "POST /api/v1/pet-life/households (name required)",
    "blocking": true,
    "source": "patch-corrections",
    "next": "G5-ONB-02",
    "noSkip": true
  },
  {
    "id": "G5-ONB-02",
    "flow": "ONB",
    "titleFa": "ثبت پت: نام و گونه",
    "titleEn": "minimal pet creation",
    "route": "/onboarding/pet",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createPet",
    "backendOp": "POST /api/v1/pet-life/households/{household_id}/pets",
    "blocking": true,
    "source": "openapi.json",
    "next": "G5-ONB-03",
    "noSkip": true
  },
  {
    "id": "G5-ONB-03",
    "flow": "ONB",
    "titleFa": "تاریخ تولد (اختیاری — قابل رد کردن)",
    "titleEn": "optional birth date, skippable",
    "route": "/onboarding/pet/birth-date",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "updatePetProfile",
    "backendOp": "PATCH /api/v1/pet-life/pets/{pet_id}/profile",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ONB-04",
    "skippable": true
  },
  {
    "id": "G5-ONB-04",
    "flow": "ONB",
    "titleFa": "ثبت آدرس (الزامی — برچسب، نام گیرنده، موبایل گیرنده، استان، شهر، آدرس؛ کدپستی اختیاری)",
    "titleEn": "address required fields",
    "route": "/onboarding/address",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createAddress",
    "backendOp": "POST /api/v1/pet-life/households/{household_id}/addresses",
    "blocking": true,
    "source": "patch-corrections",
    "next": "G5-BRIDGE-01",
    "noSkip": true
  },
  {
    "id": "G5-ONB-05",
    "flow": "ONB",
    "titleFa": "قوانین رد کردن اطلاعات اختیاری",
    "titleEn": "skip rules — only birth date is skippable",
    "route": "/onboarding",
    "kind": "settings-list",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "—",
    "blocking": false,
    "source": "patch-corrections"
  },
  {
    "id": "G5-ONB-06",
    "flow": "ONB",
    "titleFa": "بارگذاری برای کاربر بازگشتی",
    "titleEn": "returning-user bootstrap",
    "route": "/onboarding/bootstrap",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getMeContext",
    "backendOp": "GET /api/v1/me/context (accessible households, active pets, default household, onboarding requirements, routing flags)",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-BRIDGE-01",
    "branches": [
      "G5-ONB-07",
      "G5-ONB-08",
      "G5-BRIDGE-02",
      "G5-ONB-10"
    ]
  },
  {
    "id": "G5-ONB-07",
    "flow": "ONB",
    "titleFa": "خانوار موجود، بدون پت",
    "titleEn": "household exists, no pet",
    "route": "/onboarding/pet",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "—",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ONB-02"
  },
  {
    "id": "G5-ONB-08",
    "flow": "ONB",
    "titleFa": "خانوار موجود، بدون آدرس",
    "titleEn": "household exists, no address",
    "route": "/onboarding/address",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/addresses (empty)",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ONB-04"
  },
  {
    "id": "G5-ONB-09",
    "flow": "ONB",
    "titleFa": "انتخاب از میان چند پت",
    "titleEn": "multiple-pet selection",
    "route": "/today",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listHouseholdPets",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/pets",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-01"
  },
  {
    "id": "G5-ONB-10",
    "flow": "ONB",
    "titleFa": "خطا و تلاش مجدد",
    "titleEn": "onboarding failure/retry",
    "route": "/onboarding",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "retry",
    "backendOp": "same endpoint retried",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-SHOP-01",
    "flow": "SHOP",
    "titleFa": "صفحه اصلی فروشگاه",
    "titleEn": "shop landing",
    "route": "/shop",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOffers",
    "backendOp": "GET /api/v1/catalog/offers",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-SHOP-02"
  },
  {
    "id": "G5-SHOP-02",
    "flow": "SHOP",
    "titleFa": "فهرست پیشنهادهای موجود",
    "titleEn": "available offer list",
    "route": "/shop",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOffers",
    "backendOp": "GET /api/v1/catalog/offers (no query params)",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-SHOP-04"
  },
  {
    "id": "G5-SHOP-03a",
    "flow": "SHOP",
    "titleFa": "فهرست — در حال بارگذاری",
    "titleEn": "loading",
    "route": "/shop",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOffers",
    "backendOp": "GET /api/v1/catalog/offers",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-03b",
    "flow": "SHOP",
    "titleFa": "فهرست — خالی",
    "titleEn": "empty",
    "route": "/shop",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOffers",
    "backendOp": "GET /api/v1/catalog/offers",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-03c",
    "flow": "SHOP",
    "titleFa": "فهرست — خطا",
    "titleEn": "error",
    "route": "/shop",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOffers",
    "backendOp": "GET /api/v1/catalog/offers",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-04",
    "flow": "SHOP",
    "titleFa": "جزئیات محصول — قیمت/واحد/اعتماد/ماندگاری/وضعیت",
    "titleEn": "product detail, all required fields",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getOfferDetail",
    "backendOp": "GET /api/v1/catalog/offers/{offer_id} (media, saving_percent field now backend-provided, availability enum available|temporarily_unavailable)",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-CHK-01"
  },
  {
    "id": "G5-SHOP-05",
    "flow": "SHOP",
    "titleFa": "مقایسه محصول",
    "titleEn": "comparison",
    "route": "/shop/offer/:offerId/compare",
    "kind": "compare",
    "k8": "gap",
    "k9": "K9.1",
    "disposition": "local",
    "command": "—",
    "backendOp": "client-side only",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-SHOP-06",
    "flow": "SHOP",
    "titleFa": "وضعیت موجود/ناموجود",
    "titleEn": "availability status",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getOfferDetail",
    "backendOp": "GET /api/v1/catalog/offers/{offer_id} - availability strictly available|temporarily_unavailable (corrected enum)",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-SHOP-07",
    "flow": "SHOP",
    "titleFa": "پنل اعتماد: تأییدشده توسط تأمین‌کننده",
    "titleEn": "trust panel",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "OfferResponse.authenticity",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-08",
    "flow": "SHOP",
    "titleFa": "کشور تأمین‌کننده، هویت محرمانه",
    "titleEn": "supplier country, private identity",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "OfferResponse.supplier_country",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-09",
    "flow": "SHOP",
    "titleFa": "مقایسه قیمت مرجع (تاریخ‌دار)",
    "titleEn": "dated reference-price comparison",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "OfferDetailResponse.saving_percent is backend-computed (integer floor percent) - corrected from prior \"computed client-side\" note",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-10",
    "flow": "SHOP",
    "titleFa": "حداقل ضمانت ماندگاری",
    "titleEn": "minimum shelf-life guarantee",
    "route": "/shop/offer/:offerId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "OfferResponse.minimum_shelf_life_months",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-11",
    "flow": "SHOP",
    "titleFa": "تاریخ انقضای دقیق پس از تأمین",
    "titleEn": "exact expiry after sourcing",
    "route": "/orders/:orderId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/orders/{order_id} + /journey (sourced-unit exact expiry)",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-SHOP-12",
    "flow": "SHOP",
    "titleFa": "انتخاب تعداد",
    "titleEn": "quantity selection",
    "route": "/shop/offer/:offerId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "setCartQuantity",
    "backendOp": "server-enforced 1–100 at checkout",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-SHOP-13",
    "flow": "SHOP",
    "titleFa": "نمایش محصول جایگزین",
    "titleEn": "alternative product presentation",
    "route": "/shop",
    "kind": "list",
    "k8": "gap",
    "k9": "K9.1",
    "disposition": "deferred",
    "command": "—",
    "backendOp": "no alternatives relation",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-SHOP-14",
    "flow": "SHOP",
    "titleFa": "نتیجه‌ای یافت نشد",
    "titleEn": "no-results",
    "route": "/shop/search",
    "kind": "empty",
    "k8": "gap",
    "k9": "K9.1",
    "disposition": "local",
    "command": "—",
    "backendOp": "client-side search only",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-CHK-01",
    "flow": "CHK",
    "titleFa": "سبد خرید",
    "titleEn": "cart",
    "route": "/cart",
    "kind": "cart",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "frontend-local until checkout",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-05"
  },
  {
    "id": "G5-CHK-02",
    "flow": "CHK",
    "titleFa": "سبد خرید خالی",
    "titleEn": "empty cart",
    "route": "/cart",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "frontend-local",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-SHOP-01"
  },
  {
    "id": "G5-CHK-03",
    "flow": "CHK",
    "titleFa": "تغییر تعداد و حذف",
    "titleEn": "quantity change/removal",
    "route": "/cart",
    "kind": "cart",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "setCartQuantity/removeCartItem",
    "backendOp": "frontend-local",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-CHK-04",
    "flow": "CHK",
    "titleFa": "تداخل ظرفیت یا موجودی",
    "titleEn": "capacity/availability conflict",
    "route": "/checkout/review",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createOrder",
    "backendOp": "POST /api/v1/checkout/orders (4xx)",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-CHK-05",
    "flow": "CHK",
    "titleFa": "انتخاب آدرس تحویل",
    "titleEn": "address selection",
    "route": "/checkout/address",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listAddresses",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/addresses",
    "blocking": true,
    "source": "openapi.json",
    "next": "G5-CHK-07"
  },
  {
    "id": "G5-CHK-06",
    "flow": "CHK",
    "titleFa": "افزودن آدرس جدید (برچسب، نام گیرنده، موبایل گیرنده، استان، شهر، آدرس؛ کدپستی اختیاری)",
    "titleEn": "add address, required fields",
    "route": "/checkout/address",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createAddress",
    "backendOp": "POST /api/v1/pet-life/households/{household_id}/addresses",
    "blocking": true,
    "source": "patch-corrections",
    "next": "G5-CHK-07",
    "noSkip": true
  },
  {
    "id": "G5-CHK-07",
    "flow": "CHK",
    "titleFa": "بازبینی نهایی خرید",
    "titleEn": "checkout review",
    "route": "/checkout/review",
    "kind": "checkout-review",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "composed client-side from cart + address",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-09"
  },
  {
    "id": "G5-CHK-08",
    "flow": "CHK",
    "titleFa": "نمایش قیمت (ریال، فرمت‌کننده مرکزی — بدون تبدیل ثابت)",
    "titleEn": "price/currency presentation",
    "route": "/checkout/review",
    "kind": "checkout-review",
    "k8": "implement",
    "k9": null,
    "disposition": "gated",
    "command": "—",
    "backendOp": "price_irr sums; display unit from policy",
    "blocking": false,
    "source": "patch-corrections"
  },
  {
    "id": "G5-CHK-09",
    "flow": "CHK",
    "titleFa": "آغاز پرداخت",
    "titleEn": "payment initiation",
    "route": "/checkout/review",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createOrder → initiatePayment",
    "backendOp": "POST /api/v1/checkout/orders (Idempotency-Key) → POST /api/v1/orders/{order_id}/payments/zarinpal",
    "blocking": true,
    "source": "openapi.json",
    "next": "G5-CHK-10"
  },
  {
    "id": "G5-CHK-10",
    "flow": "CHK",
    "titleFa": "انتقال به درگاه زرین‌پال",
    "titleEn": "redirecting to Zarinpal",
    "route": "/checkout/payment/redirect",
    "kind": "payment-redirect",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "redirect to Zarinpal authority URL",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-11"
  },
  {
    "id": "G5-CHK-11",
    "flow": "CHK",
    "titleFa": "بازگشت از زرین‌پال",
    "titleEn": "returning from Zarinpal",
    "route": "/checkout/payment/return",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/payments/zarinpal/callback",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-12",
    "branches": [
      "G5-CHK-13",
      "G5-CHK-14",
      "G5-CHK-15"
    ]
  },
  {
    "id": "G5-CHK-12",
    "flow": "CHK",
    "titleFa": "پرداخت تأییدشده",
    "titleEn": "verified payment",
    "route": "/checkout/confirmation",
    "kind": "payment-result",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "callback verified → order paid",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-18"
  },
  {
    "id": "G5-CHK-13",
    "flow": "CHK",
    "titleFa": "پرداخت لغوشده",
    "titleEn": "cancelled payment",
    "route": "/checkout/payment/return",
    "kind": "payment-result",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "callback cancelled",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-16"
  },
  {
    "id": "G5-CHK-14",
    "flow": "CHK",
    "titleFa": "پرداخت ناموفق",
    "titleEn": "failed payment",
    "route": "/checkout/payment/return",
    "kind": "payment-result",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "callback failed",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-16"
  },
  {
    "id": "G5-CHK-15",
    "flow": "CHK",
    "titleFa": "وضعیت نامشخص تأیید پرداخت",
    "titleEn": "uncertain verification",
    "route": "/checkout/payment/return",
    "kind": "payment-result",
    "tone": "info",
    "k8": "gap",
    "k9": "K9.residual",
    "disposition": "gated",
    "command": "—",
    "backendOp": "No customer reconciliation endpoint - calm pending state only, passive refresh, safe nav to order/Today, optional support contact",
    "blocking": true,
    "source": "K9 ADR-004 (payment reconciliation stays operator-only)",
    "next": "G5-CHK-16"
  },
  {
    "id": "G5-CHK-16",
    "flow": "CHK",
    "titleFa": "تلاش مجدد برای پرداخت",
    "titleEn": "retry payment",
    "route": "/checkout/review",
    "kind": "checkout-review",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "initiatePayment",
    "backendOp": "POST /api/v1/orders/{order_id}/payments/zarinpal",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-CHK-09"
  },
  {
    "id": "G5-CHK-17",
    "flow": "CHK",
    "titleFa": "جلوگیری از ثبت تکراری (Idempotency-Key)",
    "titleEn": "duplicate-submit prevention",
    "route": "/checkout/review",
    "kind": "checkout-review",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createOrder",
    "backendOp": "Idempotency-Key header, required",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-CHK-18",
    "flow": "CHK",
    "titleFa": "تأیید نهایی سفارش (تاریخ از backend)",
    "titleEn": "order confirmation, backend timestamps only",
    "route": "/checkout/confirmation",
    "kind": "confirmation",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "OrderResponse + GET /api/v1/orders/{order_id}/journey (delivery_commitment_at)",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-ORD-05"
  },
  {
    "id": "G5-ORD-01",
    "flow": "ORD",
    "titleFa": "تاریخچه سفارش‌ها",
    "titleEn": "order history, real row hierarchy",
    "route": "/orders",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOrders",
    "backendOp": "GET /api/v1/orders",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ORD-05"
  },
  {
    "id": "G5-ORD-02",
    "flow": "ORD",
    "titleFa": "تاریخچه خالی",
    "titleEn": "empty order history",
    "route": "/orders",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOrders",
    "backendOp": "GET /api/v1/orders",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ORD-03",
    "flow": "ORD",
    "titleFa": "صفحه‌بندی / بارگذاری بیشتر",
    "titleEn": "paginated loading-more",
    "route": "/orders",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listOrders/feed",
    "backendOp": "GET /api/v1/orders · /orders/feed",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ORD-04",
    "flow": "ORD",
    "titleFa": "خلاصه سفارش",
    "titleEn": "order summary",
    "route": "/orders",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/orders (list fields)",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ORD-05",
    "flow": "ORD",
    "titleFa": "جزئیات سفارش (order_id, status, delivery_commitment_at, delivered_at, timeline, sourced_units)",
    "titleEn": "order detail, K8 fields only",
    "route": "/orders/:orderId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getOrder / setPetPlan",
    "backendOp": "GET /api/v1/orders/{order_id} (reload-safe projection) - PUT /api/v1/orders/{order_id}/pet-plan (idempotent, no inventory/estimation effect)",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-ORD-07"
  },
  {
    "id": "G5-ORD-06",
    "flow": "ORD",
    "titleFa": "وضعیت پرداخت",
    "titleEn": "payment state",
    "route": "/orders/:orderId",
    "kind": "timeline",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/orders/{order_id}/journey",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ORD-07",
    "flow": "ORD",
    "titleFa": "وضعیت تأمین کالا",
    "titleEn": "sourcing state",
    "route": "/orders/:orderId",
    "kind": "timeline",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/orders/{order_id}/journey (sourced_units)",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ORD-09"
  },
  {
    "id": "G5-ORD-08",
    "flow": "ORD",
    "titleFa": "مدرک اعتماد واحد تأمین‌شده",
    "titleEn": "sourced-unit trust evidence",
    "route": "/orders/:orderId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "sourced_units fields",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ORD-09",
    "flow": "ORD",
    "titleFa": "تاریخ انقضای دقیق",
    "titleEn": "exact expiry",
    "route": "/orders/:orderId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "sourced_units exact expiry (if present)",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ORD-10"
  },
  {
    "id": "G5-ORD-10",
    "flow": "ORD",
    "titleFa": "مسیر ارسال (در حال حمل)",
    "titleEn": "in-transit timeline",
    "route": "/orders/:orderId",
    "kind": "timeline",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getOrderJourney",
    "backendOp": "GET /api/v1/orders/{order_id}/journey",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ORD-12",
    "branches": [
      "G5-ORD-11"
    ]
  },
  {
    "id": "G5-ORD-11",
    "flow": "ORD",
    "titleFa": "سفارش تأخیردار — تاریخ اصلی و تاریخ اصلاح‌شده (از backend)",
    "titleEn": "delayed, literal original+revised dates",
    "route": "/orders/:orderId",
    "kind": "timeline",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "acknowledgeDelay",
    "backendOp": "GET /api/v1/orders/{order_id}/journey timeline (original+revised commitment events) - POST /api/v1/orders/{order_id}/delay-acknowledgements (Idempotency-Key; implies no compensation/cancellation/waiver)",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-ORD-12",
    "flow": "ORD",
    "titleFa": "تحویل داده‌شده",
    "titleEn": "delivered state",
    "route": "/orders/:orderId",
    "kind": "timeline",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getOrderJourney",
    "backendOp": "delivered_at + household inventory created",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-BRIDGE-14"
  },
  {
    "id": "G5-ORD-13",
    "flow": "ORD",
    "titleFa": "شکست در تأمین (بدون وعده حل)",
    "titleEn": "failed sourcing, no resolution promise",
    "route": "/orders/:orderId",
    "kind": "error-block",
    "tone": "error",
    "k8": "gap",
    "k9": null,
    "disposition": "gated",
    "command": "—",
    "backendOp": "operator resolutions are awaiting_policy only",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ACC-01",
    "flow": "ACC",
    "titleFa": "صفحه اصلی حساب",
    "titleEn": "account home, all destinations",
    "route": "/account",
    "kind": "account-home",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "composed from onboarding + Today data",
    "blocking": false,
    "source": "design-contract",
    "next": "G5-ACC-10"
  },
  {
    "id": "G5-ACC-02",
    "flow": "ACC",
    "titleFa": "پت‌ها",
    "titleEn": "pets",
    "route": "/account/pets",
    "kind": "settings-list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listHouseholdPets",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/pets (deterministically ordered)",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md"
  },
  {
    "id": "G5-ACC-03",
    "flow": "ACC",
    "titleFa": "آدرس‌های تحویل",
    "titleEn": "addresses",
    "route": "/account/addresses",
    "kind": "settings-list",
    "k8": "implement",
    "k9": "K9.1",
    "disposition": "implement",
    "command": "listAddresses",
    "backendOp": "GET addresses; no PATCH/DELETE yet",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ACC-04",
    "flow": "ACC",
    "titleFa": "ورودی تاریخچه سفارش‌ها",
    "titleEn": "order-history entry",
    "route": "/account",
    "kind": "settings-list",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "frontend navigation",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-ACC-05",
    "flow": "ACC",
    "titleFa": "ورودی اعلان‌ها",
    "titleEn": "notification entry",
    "route": "/account",
    "kind": "settings-list",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "frontend navigation",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-ACC-06",
    "flow": "ACC",
    "titleFa": "تنظیمات پیامک و ساعات سکوت (تاگل رویداد + quiet_start_local/quiet_end_local)",
    "titleEn": "SMS + quiet hours, write exists, no GET",
    "route": "/account/notifications/preferences",
    "kind": "settings-list",
    "k8": "implement",
    "k9": "K9.residual",
    "disposition": "deferred",
    "command": "setSmsPreference",
    "backendOp": "PUT preferences/{event_key}/sms writes quiet_start_local/quiet_end_local; no GET in K9 openapi.json - launch-hidden/deferred, excluded from Account nav, never customer-renderable from guesses/localStorage",
    "blocking": false,
    "source": "K9 openapi.json (confirmed no read endpoint)"
  },
  {
    "id": "G5-ACC-07",
    "flow": "ACC",
    "titleFa": "موجودی کیف پول",
    "titleEn": "wallet balance only",
    "route": "/account/wallet",
    "kind": "wallet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getWallet",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/wallet",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ACC-08",
    "flow": "ACC",
    "titleFa": "ورودی حریم خصوصی",
    "titleEn": "privacy entry → export / disable",
    "route": "/account/privacy",
    "kind": "settings-list",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "frontend navigation",
    "blocking": false,
    "source": "design-contract",
    "next": "G5-ACC-14"
  },
  {
    "id": "G5-ACC-09",
    "flow": "ACC",
    "titleFa": "خروج از حساب",
    "titleEn": "logout",
    "route": "/account",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "logout",
    "backendOp": "POST /api/v1/auth/session/logout",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ACC-10",
    "flow": "ACC",
    "titleFa": "صندوق اعلان‌ها",
    "titleEn": "notification inbox",
    "route": "/account/notifications",
    "kind": "inbox",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listNotifications",
    "backendOp": "GET /api/v1/pet-life/notifications · /feed",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ACC-11"
  },
  {
    "id": "G5-ACC-11",
    "flow": "ACC",
    "titleFa": "وضعیت خوانده/نخوانده",
    "titleEn": "unread/read",
    "route": "/account/notifications",
    "kind": "inbox",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "markNotificationRead",
    "backendOp": "POST /api/v1/pet-life/notifications/{notification_id}/read",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ACC-06"
  },
  {
    "id": "G5-ACC-12",
    "flow": "ACC",
    "titleFa": "صندوق اعلان خالی",
    "titleEn": "empty inbox",
    "route": "/account/notifications",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listNotifications",
    "backendOp": "GET /api/v1/pet-life/notifications",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-ACC-13",
    "flow": "ACC",
    "titleFa": "جزئیات و مقصد اعلان",
    "titleEn": "notification detail/destination",
    "route": "/account/notifications",
    "kind": "detail",
    "k8": "gap",
    "k9": "K9.1",
    "disposition": "gated",
    "command": "—",
    "backendOp": "destination-route field unconfirmed",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-ACC-14",
    "flow": "ACC",
    "titleFa": "خروجی داده‌های شخصی (export)",
    "titleEn": "personal-data export, separate from disable",
    "route": "/account/privacy",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "exportData",
    "backendOp": "GET /api/v1/privacy/export",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ACC-15"
  },
  {
    "id": "G5-ACC-15",
    "flow": "ACC",
    "titleFa": "درخواست غیرفعال‌سازی/ناشناس‌سازی حساب",
    "titleEn": "disable/anonymize request, separate from export",
    "route": "/account/privacy",
    "kind": "sheet",
    "k8": "gap",
    "k9": null,
    "disposition": "gated",
    "command": "submitPrivacyRequest",
    "backendOp": "POST /api/v1/privacy/requests → operator /operator/privacy/requests/{request_id}/disable",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-ACC-16"
  },
  {
    "id": "G5-ACC-16",
    "flow": "ACC",
    "titleFa": "تأیید و وضعیت در انتظار درخواست",
    "titleEn": "confirmation + pending-request state",
    "route": "/account/privacy",
    "kind": "sheet",
    "k8": "gap",
    "k9": null,
    "disposition": "gated",
    "command": "—",
    "backendOp": "operator-executed, pending until disabled",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-BRIDGE-01",
    "flow": "BRIDGE",
    "titleFa": "امروز",
    "titleEn": "Today: PetSwitcher, FoodModule, ≤1 event, 76px Garden strip, bottom nav",
    "route": "/today",
    "kind": "today",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today",
    "blocking": false,
    "source": "design-contract",
    "next": "G5-SHOP-01"
  },
  {
    "id": "G5-BRIDGE-02",
    "flow": "BRIDGE",
    "titleFa": "نبود بستر خانوار",
    "titleEn": "missing household context",
    "route": "/today",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getMeContext",
    "backendOp": "GET /api/v1/me/context routing flags resolve missing-household case",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-03",
    "flow": "BRIDGE",
    "titleFa": "نبود بستر پت",
    "titleEn": "missing pet context",
    "route": "/today",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today requires pet_id",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-BRIDGE-04",
    "flow": "BRIDGE",
    "titleFa": "بدون پت",
    "titleEn": "no pets",
    "route": "/today",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "—",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-BRIDGE-05",
    "flow": "BRIDGE",
    "titleFa": "بدون موجودی انبار",
    "titleEn": "no inventory",
    "route": "/inventory",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listInventory",
    "backendOp": "GET /api/v1/pet-life/households/{household_id}/inventory",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-BRIDGE-06",
    "flow": "BRIDGE",
    "titleFa": "بسته‌بندی بازنشده",
    "titleEn": "unopened inventory",
    "route": "/inventory/:unitId",
    "kind": "meter",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listInventory",
    "backendOp": "GET /api/v1/pet-life/inventory/{unit_id} (typed detail: unit, source/state facts, expiry snapshot, assignments, shares_known)",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-BRIDGE-14"
  },
  {
    "id": "G5-BRIDGE-07",
    "flow": "BRIDGE",
    "titleFa": "بازشده، اطلاعات تخمین ناکافی",
    "titleEn": "opened, insufficient estimate info",
    "route": "/inventory/:unitId",
    "kind": "meter",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "setConsumptionKnowledge",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/open - level mode returns founder-approved gram bounds (0-25/25-50/50-75/75-100%); exact grams remain unknown, never computed client-side",
    "blocking": false,
    "source": "K9 ADR-004",
    "next": "G5-BRIDGE-08",
    "branches": [
      "G5-BRIDGE-09"
    ]
  },
  {
    "id": "G5-BRIDGE-08",
    "flow": "BRIDGE",
    "titleFa": "تخمین فعال",
    "titleEn": "active estimate, known share",
    "route": "/today",
    "kind": "meter",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today",
    "blocking": false,
    "source": "openapi.json",
    "next": "G5-BRIDGE-01"
  },
  {
    "id": "G5-BRIDGE-09",
    "flow": "BRIDGE",
    "titleFa": "سهم نامشخص خانوار — بازه راه‌راه، بدون عدد سرانه",
    "titleEn": "unknown shares, striped band, no per-pet number",
    "route": "/today",
    "kind": "meter",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "scope=household, sharesKnown=false",
    "blocking": false,
    "source": "patch-corrections",
    "next": "G5-BRIDGE-01"
  },
  {
    "id": "G5-BRIDGE-10",
    "flow": "BRIDGE",
    "titleFa": "موجودی «exhausted» (نه finished)",
    "titleEn": "exhausted inventory, corrected terminology",
    "route": "/inventory/:unitId",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "exhaustInventory",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/exhaust",
    "blocking": false,
    "source": "patch-corrections"
  },
  {
    "id": "G5-BRIDGE-11",
    "flow": "BRIDGE",
    "titleFa": "خطای موضعی یک ماژول",
    "titleEn": "local module failure",
    "route": "/today",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "local",
    "command": "—",
    "backendOp": "per-module fetch failure",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-BRIDGE-12",
    "flow": "BRIDGE",
    "titleFa": "خطای کامل احراز هویت صفحه",
    "titleEn": "full-page auth failure",
    "route": "/today",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "refreshSession → re-auth",
    "backendOp": "POST /api/v1/auth/session/refresh (fails)",
    "blocking": false,
    "source": "openapi.json"
  },
  {
    "id": "G5-BRIDGE-13",
    "flow": "BRIDGE",
    "titleFa": "داده قدیمی / در حال به‌روزرسانی",
    "titleEn": "stale/reloading",
    "route": "/today",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday (revalidate)",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today",
    "blocking": false,
    "source": "design-contract"
  },
  {
    "id": "G5-BRIDGE-14",
    "flow": "BRIDGE",
    "titleFa": "جزئیات واحد انبار (/inventory/:unitId — «باز کردن» به‌صورت sheet)",
    "titleEn": "inventory unit detail, opening as sheet action",
    "route": "/inventory/:unitId",
    "kind": "inventory-unit",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "confirmInventoryOpening",
    "backendOp": "GET /api/v1/pet-life/inventory/{unit_id} (typed detail)",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-BRIDGE-07"
  },
  {
    "id": "G5-BRIDGE-15",
    "flow": "BRIDGE",
    "titleFa": "امروز — بدون غذا (none)",
    "titleEn": "Today food.state=none",
    "route": "/today",
    "kind": "today-food",
    "tone": null,
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=none",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-16",
    "flow": "BRIDGE",
    "titleFa": "امروز — در راه (incoming)",
    "titleEn": "Today food.state=incoming, planned pets only, no remaining-days",
    "route": "/today",
    "kind": "today-food",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=incoming; appears only for pets named in an order-line plan; no remaining-days field",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-17",
    "flow": "BRIDGE",
    "titleFa": "امروز — باز‌نشده (unopened)",
    "titleEn": "Today food.state=unopened, no remaining-days",
    "route": "/today",
    "kind": "today-food",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=unopened; no remaining-days field",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-18",
    "flow": "BRIDGE",
    "titleFa": "امروز — تخمین نامشخص (unknown_estimate)",
    "titleEn": "Today food.state=unknown_estimate, no pet-level number",
    "route": "/today",
    "kind": "today-food",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=unknown_estimate; unknown shares never produce a pet-level remaining-days value",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-19",
    "flow": "BRIDGE",
    "titleFa": "امروز — تخمین فعال (estimated)",
    "titleEn": "Today food.state=estimated",
    "route": "/today",
    "kind": "today-food",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=estimated",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-20",
    "flow": "BRIDGE",
    "titleFa": "امروز — ناموجود (unavailable)",
    "titleEn": "Today food.state=unavailable",
    "route": "/today",
    "kind": "today-food",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - food.state=unavailable",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-21",
    "flow": "BRIDGE",
    "titleFa": "توجه: شکست در تأمین",
    "titleEn": "primary_attention: sourcing failure",
    "route": "/today",
    "kind": "attention",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=sourcing_failed",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-22",
    "flow": "BRIDGE",
    "titleFa": "توجه: تأخیر تحویل (delivery_delayed)",
    "titleEn": "primary_attention.type=delivery_delayed",
    "route": "/today",
    "kind": "attention",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=delivery_delayed (TodayDeliveryDelayedAttention)",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-23",
    "flow": "BRIDGE",
    "titleFa": "توجه: تأیید باز کردن",
    "titleEn": "primary_attention: confirm opening",
    "route": "/today",
    "kind": "attention",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "confirmInventoryOpening",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=confirm_opening -> POST /api/v1/pet-life/inventory/{unit_id}/open",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-24",
    "flow": "BRIDGE",
    "titleFa": "توجه: بهبود تخمین",
    "titleEn": "primary_attention: improve estimate",
    "route": "/today",
    "kind": "attention",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "correctRemainingAmount",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=improve_food_estimate -> POST /api/v1/pet-life/inventory/{unit_id}/estimate/correct",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-25",
    "flow": "BRIDGE",
    "titleFa": "وضعیت تجدید سفارش: اکنون سفارش دهید",
    "titleEn": "reorder outcome=order_now",
    "route": "/inventory/:unitId",
    "kind": "reorder",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "assessReorder",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - outcome=order_now",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-SHOP-01"
  },
  {
    "id": "G5-BRIDGE-26",
    "flow": "BRIDGE",
    "titleFa": "وضعیت تجدید سفارش: هنوز نه",
    "titleEn": "reorder outcome=not_yet",
    "route": "/inventory/:unitId",
    "kind": "reorder",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "assessReorder",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - outcome=not_yet",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-27",
    "flow": "BRIDGE",
    "titleFa": "وضعیت تجدید سفارش: به‌خواب رفته (حداکثر ۷۲ ساعت)",
    "titleEn": "reorder outcome=snoozed, max 72h, server-owned",
    "route": "/inventory/:unitId",
    "kind": "reorder",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "assessReorder",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - outcome=snoozed; PUT /api/v1/pet-life/inventory/{unit_id}/reorder-snooze is durable/idempotent, max 72h, server-owned expiry and early-break",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-28",
    "flow": "BRIDGE",
    "titleFa": "وضعیت تجدید سفارش: مسدود توسط سیاست",
    "titleEn": "reorder outcome=policy_blocked",
    "route": "/inventory/:unitId",
    "kind": "reorder",
    "tone": "warning",
    "k8": "implement",
    "k9": null,
    "disposition": "gated",
    "command": "assessReorder",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - outcome=policy_blocked",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-29",
    "flow": "BRIDGE",
    "titleFa": "وضعیت تجدید سفارش: اطلاعات ناکافی",
    "titleEn": "reorder outcome=insufficient_facts",
    "route": "/inventory/:unitId",
    "kind": "reorder",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "assessReorder",
    "backendOp": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - outcome=insufficient_facts",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-30",
    "flow": "BRIDGE",
    "titleFa": "تأیید به‌خواب بردن یادآوری تجدید سفارش",
    "titleEn": "reorder snooze confirmation, max 72h",
    "route": "/inventory/:unitId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "snoozeReorder",
    "backendOp": "PUT /api/v1/pet-life/inventory/{unit_id}/reorder-snooze",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-BRIDGE-01"
  },
  {
    "id": "G5-BRIDGE-31",
    "flow": "BRIDGE",
    "titleFa": "باغ ایرانی — خالی",
    "titleEn": "Garden empty state",
    "route": "/garden/:petId",
    "kind": "garden",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getGarden",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/garden",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-32"
  },
  {
    "id": "G5-BRIDGE-32",
    "flow": "BRIDGE",
    "titleFa": "باغ ایرانی — کامل/برقرارشده",
    "titleEn": "Garden full/established state, no XP/streak/decay/purchase reward",
    "route": "/garden/:petId",
    "kind": "garden",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getGarden",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/garden - server-derived, no client-created eligibility",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-33"
  },
  {
    "id": "G5-BRIDGE-33",
    "flow": "BRIDGE",
    "titleFa": "باغ ایرانی — جای‌گذاری شیء",
    "titleEn": "Garden object placement",
    "route": "/garden/:petId",
    "kind": "garden",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "placeGardenObject",
    "backendOp": "PUT /api/v1/pet-life/garden/{reward_id}/placement",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-34"
  },
  {
    "id": "G5-BRIDGE-34",
    "flow": "BRIDGE",
    "titleFa": "باغ ایرانی — جابه‌جایی شیء",
    "titleEn": "Garden object movement",
    "route": "/garden/:petId",
    "kind": "garden",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "placeGardenObject",
    "backendOp": "PUT /api/v1/pet-life/garden/{reward_id}/placement",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-35"
  },
  {
    "id": "G5-BRIDGE-35",
    "flow": "BRIDGE",
    "titleFa": "باغ ایرانی — بازگشت به انبار",
    "titleEn": "Garden return-to-storage, memory link preserved",
    "route": "/garden/:petId",
    "kind": "garden",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "returnGardenObject",
    "backendOp": "DELETE /api/v1/pet-life/garden/{reward_id}/placement - stores object, preserves memory link",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md",
    "next": "G5-BRIDGE-01"
  },
  {
    "id": "G5-SHOP-15",
    "flow": "SHOP",
    "titleFa": "اشتراک اطلاع‌رسانی موجودی",
    "titleEn": "availability subscribe",
    "route": "/shop/offer/:offerId",
    "kind": "subscribe",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "subscribeAvailability",
    "backendOp": "POST /api/v1/catalog/offers/{offer_id}/availability-subscriptions - order_created=false always",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-SHOP-16"
  },
  {
    "id": "G5-SHOP-16",
    "flow": "SHOP",
    "titleFa": "اشتراک فعال شد",
    "titleEn": "subscribed confirmation, no order created",
    "route": "/shop/offer/:offerId",
    "kind": "subscribe",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "GET /api/v1/me/availability-subscriptions",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-SHOP-17",
    "flow": "SHOP",
    "titleFa": "لغو اشتراک",
    "titleEn": "unsubscribe",
    "route": "/shop/offer/:offerId",
    "kind": "subscribe",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "unsubscribeAvailability",
    "backendOp": "DELETE /api/v1/catalog/offers/{offer_id}/availability-subscriptions",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-SHOP-18",
    "flow": "SHOP",
    "titleFa": "خطا در اشتراک",
    "titleEn": "subscribe error",
    "route": "/shop/offer/:offerId",
    "kind": "subscribe",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "subscribeAvailability",
    "backendOp": "POST /api/v1/catalog/offers/{offer_id}/availability-subscriptions (4xx)",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-SUPPORT-01",
    "flow": "SUPPORT",
    "titleFa": "ثبت درخواست پشتیبانی/کانسیرژ",
    "titleEn": "create support/concierge request",
    "route": "/support/new",
    "kind": "form",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "createCustomerRequest",
    "backendOp": "POST /api/v1/customer-requests (Idempotency-Key; type=support|concierge_sourcing)",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-SUPPORT-02"
  },
  {
    "id": "G5-SUPPORT-02",
    "flow": "SUPPORT",
    "titleFa": "تأیید ثبت درخواست (متن دقیق سرور)",
    "titleEn": "acknowledgement, verbatim backend text, no promises",
    "route": "/support/new",
    "kind": "ack",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "response.acknowledgement_fa rendered verbatim; explicit false promises for availability/price/response-time/sourcing",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-SUPPORT-03"
  },
  {
    "id": "G5-SUPPORT-03",
    "flow": "SUPPORT",
    "titleFa": "فهرست درخواست‌ها",
    "titleEn": "request list",
    "route": "/support",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listCustomerRequests",
    "backendOp": "GET /api/v1/customer-requests",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-SUPPORT-04"
  },
  {
    "id": "G5-SUPPORT-04",
    "flow": "SUPPORT",
    "titleFa": "جزئیات و وضعیت درخواست",
    "titleEn": "request detail/status",
    "route": "/support/:requestId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getCustomerRequest",
    "backendOp": "GET /api/v1/customer-requests/{request_id}",
    "blocking": false,
    "source": "K9 frontend-integration.md"
  },
  {
    "id": "G5-BRIDGE-36",
    "flow": "BRIDGE",
    "titleFa": "توجه: عقب‌افتادگی تحویل (delivery_overdue)",
    "titleEn": "primary_attention.type=delivery_overdue, distinct from delayed",
    "route": "/today",
    "kind": "attention",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=delivery_overdue (TodayDeliveryOverdueAttention)",
    "blocking": false,
    "source": "K9 openapi.json TodayDeliveryOverdueAttention"
  },
  {
    "id": "G5-BRIDGE-37",
    "flow": "BRIDGE",
    "titleFa": "توجه: مسیر فعال مراقبتی (active_journey)",
    "titleEn": "primary_attention.type=active_journey",
    "route": "/today",
    "kind": "attention",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getToday",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/today - primary_attention.type=active_journey (TodayActiveJourneyAttention)",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-05"
  },
  {
    "id": "G5-JOURNEY-01",
    "flow": "JOURNEY",
    "titleFa": "پیشنهادهای مسیر — در حال بارگذاری",
    "titleEn": "journey offers loading",
    "route": "/journeys",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listJourneyOffers",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/journey-offers",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-02",
    "flow": "JOURNEY",
    "titleFa": "پیشنهادهای مسیر — خالی",
    "titleEn": "journey offers empty",
    "route": "/journeys",
    "kind": "empty",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listJourneyOffers",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/journey-offers",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-03",
    "flow": "JOURNEY",
    "titleFa": "پیشنهادهای مسیر — موجود",
    "titleEn": "journey offers available",
    "route": "/journeys",
    "kind": "list",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listJourneyOffers",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/journey-offers (JourneyOfferResponse[])",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-05"
  },
  {
    "id": "G5-JOURNEY-04",
    "flow": "JOURNEY",
    "titleFa": "پیشنهادهای مسیر — خطا",
    "titleEn": "journey offers error",
    "route": "/journeys",
    "kind": "error-block",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "listJourneyOffers",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/journey-offers",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-05",
    "flow": "JOURNEY",
    "titleFa": "جزئیات تعریف مسیر",
    "titleEn": "journey-definition detail; content typed as JourneyContentResponse",
    "route": "/journeys/:definitionId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getJourneyDefinition",
    "backendOp": "GET /api/v1/pet-life/journey-definitions/{definition_id} - content: JourneyContentResponse {steps: JourneyStepResponse[], completion_requirements, eligibility, active_window, exception_behavior, garden_object_key, professional_approval_ref}",
    "blocking": false,
    "source": "K9 openapi.json JourneyDefinitionResponse",
    "next": "G5-JOURNEY-06"
  },
  {
    "id": "G5-JOURNEY-06",
    "flow": "JOURNEY",
    "titleFa": "تأیید شروع مسیر",
    "titleEn": "start confirmation",
    "route": "/journeys/:definitionId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "startJourney",
    "backendOp": "POST /api/v1/pet-life/pets/{pet_id}/journeys (200, IdResponse)",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-07"
  },
  {
    "id": "G5-JOURNEY-07",
    "flow": "JOURNEY",
    "titleFa": "مسیر آغاز شد",
    "titleEn": "start success",
    "route": "/journeys/:journeyId",
    "kind": "ack",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "200 IdResponse from POST /api/v1/pet-life/pets/{pet_id}/journeys",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-08"
  },
  {
    "id": "G5-JOURNEY-08",
    "flow": "JOURNEY",
    "titleFa": "جزئیات و پیشرفت مسیر فعال",
    "titleEn": "active journey detail/progress; steps typed as JourneyStepResponse[]",
    "route": "/journeys/:journeyId",
    "kind": "journey-detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getJourney",
    "backendOp": "GET /api/v1/pet-life/journeys/{journey_id} - steps: JourneyStepResponse[] {key, title_fa, body_fa, allowed_answers: JourneyAnswerOptionResponse[]{key,label_fa}}",
    "blocking": false,
    "source": "K9 openapi.json JourneyDetailResponse",
    "next": "G5-JOURNEY-09"
  },
  {
    "id": "G5-JOURNEY-09",
    "flow": "JOURNEY",
    "titleFa": "سؤال چک-این",
    "titleEn": "check-in question; step typed as JourneyStepResponse",
    "route": "/journeys/:journeyId/check-in",
    "kind": "checkin-typed",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "JourneyCheckInBody {check_in_key, answer_key}; answer_key validated against step.allowed_answers[].key",
    "blocking": false,
    "source": "K9 openapi.json JourneyCheckInBody",
    "next": "G5-JOURNEY-10"
  },
  {
    "id": "G5-JOURNEY-10",
    "flow": "JOURNEY",
    "titleFa": "پاسخ چک-این",
    "titleEn": "check-in answer",
    "route": "/journeys/:journeyId/check-in",
    "kind": "checkin-typed",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "submitCheckIn",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/check-ins",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-11"
  },
  {
    "id": "G5-JOURNEY-11",
    "flow": "JOURNEY",
    "titleFa": "ارسال چک-این",
    "titleEn": "check-in submitting",
    "route": "/journeys/:journeyId/check-in",
    "kind": "loading",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "submitCheckIn",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/check-ins",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-12"
  },
  {
    "id": "G5-JOURNEY-12",
    "flow": "JOURNEY",
    "titleFa": "چک-این موفق",
    "titleEn": "check-in success",
    "route": "/journeys/:journeyId",
    "kind": "ack",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "—",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/check-ins (200, JourneyCheckInResponse, Idempotency-Key required)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-13",
    "flow": "JOURNEY",
    "titleFa": "خطای اعتبارسنجی چک-این",
    "titleEn": "check-in validation failure",
    "route": "/journeys/:journeyId/check-in",
    "kind": "checkin-typed",
    "tone": "error",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "submitCheckIn",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/check-ins (200; 422 if answer_key not in allowed_answers)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-14",
    "flow": "JOURNEY",
    "titleFa": "ارسال تکراری چک-این (replay)",
    "titleEn": "check-in replay, idempotent",
    "route": "/journeys/:journeyId/check-in",
    "kind": "checkin-typed",
    "tone": "info",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "submitCheckIn",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/check-ins (200, replay-safe via Idempotency-Key)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-15",
    "flow": "JOURNEY",
    "titleFa": "توقف موقت مسیر",
    "titleEn": "pause confirmation",
    "route": "/journeys/:journeyId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "pauseJourney",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/pause (204 No Content)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-16",
    "flow": "JOURNEY",
    "titleFa": "از سرگیری مسیر",
    "titleEn": "resume confirmation",
    "route": "/journeys/:journeyId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "resumeJourney",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/resume (204 No Content)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-17",
    "flow": "JOURNEY",
    "titleFa": "توقف کامل مسیر",
    "titleEn": "stop confirmation, respected outcome",
    "route": "/journeys/:journeyId",
    "kind": "sheet",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "stopJourney",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/stop (204 No Content)",
    "blocking": false,
    "source": "K9 openapi.json"
  },
  {
    "id": "G5-JOURNEY-18",
    "flow": "JOURNEY",
    "titleFa": "تکمیل مسیر — یک خاطره، یک جایزه باغ",
    "titleEn": "completion, at most one memory + one garden reward",
    "route": "/journeys/:journeyId",
    "kind": "ack",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "completeJourney",
    "backendOp": "POST /api/v1/pet-life/journeys/{journey_id}/complete (200, JourneyCompletionResponse)",
    "blocking": false,
    "source": "K9 openapi.json",
    "next": "G5-JOURNEY-19"
  },
  {
    "id": "G5-JOURNEY-19",
    "flow": "JOURNEY",
    "titleFa": "جزئیات خاطره دفترچه",
    "titleEn": "diary-memory detail",
    "route": "/diary/:entryId",
    "kind": "detail",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "getDiaryEntry",
    "backendOp": "GET /api/v1/pet-life/pets/{pet_id}/diary/{entry_id}",
    "blocking": false,
    "source": "K9 frontend-integration.md",
    "next": "G5-JOURNEY-20"
  },
  {
    "id": "G5-JOURNEY-20",
    "flow": "JOURNEY",
    "titleFa": "آشکارسازی و جای‌گذاری جایزه باغ",
    "titleEn": "garden-reward reveal + placement",
    "route": "/garden/:petId",
    "kind": "garden",
    "tone": "success",
    "k8": "implement",
    "k9": null,
    "disposition": "implement",
    "command": "placeGardenObject",
    "backendOp": "PUT /api/v1/pet-life/garden/{reward_id}/placement",
    "blocking": false,
    "source": "K9 BACKEND_FRONTEND_INTEGRATION_CONTRACT.md"
  }
];
  window.GATE52C_JOURNEYS = [
  {
    "id": "T8",
    "name": "اولین بار: ورود → خانوار → پت → آدرس → امروز",
    "main": [
      "G5-AUTH-01",
      "G5-AUTH-03",
      "G5-AUTH-04",
      "G5-ONB-01",
      "G5-ONB-02",
      "G5-ONB-03",
      "G5-ONB-04",
      "G5-BRIDGE-01"
    ]
  },
  {
    "id": "T9",
    "name": "بازگشتی: بازیابی نشست → بارگذاری → امروز → تعویض پت",
    "main": [
      "G5-AUTH-13",
      "G5-ONB-06",
      "G5-BRIDGE-01"
    ]
  },
  {
    "id": "T10",
    "name": "فروشگاه → سبد → آدرس → پرداخت → تأیید سفارش",
    "main": [
      "G5-SHOP-01",
      "G5-SHOP-04",
      "G5-CHK-01",
      "G5-CHK-05",
      "G5-CHK-07",
      "G5-CHK-10",
      "G5-CHK-12",
      "G5-CHK-18",
      "G5-ORD-05"
    ]
  },
  {
    "id": "T11",
    "name": "بازگشت از پرداخت: لغو/ناموفق/نامشخص → تلاش مجدد",
    "main": [
      "G5-CHK-11",
      "G5-CHK-13",
      "G5-CHK-16",
      "G5-CHK-09"
    ]
  },
  {
    "id": "T12",
    "name": "تاریخچه → جزئیات → تأمین → انقضا → حمل → تأخیر/تحویل",
    "main": [
      "G5-ORD-01",
      "G5-ORD-05",
      "G5-ORD-07",
      "G5-ORD-09",
      "G5-ORD-10",
      "G5-ORD-12"
    ]
  },
  {
    "id": "T13",
    "name": "حساب → اعلان‌ها → پیامک/سکوت → خروجی → غیرفعال‌سازی",
    "main": [
      "G5-ACC-01",
      "G5-ACC-10",
      "G5-ACC-11",
      "G5-ACC-06",
      "G5-ACC-14",
      "G5-ACC-15",
      "G5-ACC-16"
    ]
  },
  {
    "id": "T14",
    "name": "تحویل → واحد انبار → باز کردن → سهم دانسته/نادانسته → امروز",
    "main": [
      "G5-ORD-12",
      "G5-BRIDGE-14",
      "G5-BRIDGE-07",
      "G5-BRIDGE-08",
      "G5-BRIDGE-01"
    ]
  },
  {
    "id": "T15",
    "name": "امروز -> ارزیابی تجدید سفارش -> فروشگاه یا به‌خواب بردن",
    "main": [
      "G5-BRIDGE-01",
      "G5-BRIDGE-25",
      "G5-SHOP-01"
    ]
  },
  {
    "id": "T16",
    "name": "محصول/سفارش/حساب -> درخواست پشتیبانی -> تأیید -> تاریخچه/جزئیات",
    "main": [
      "G5-SUPPORT-01",
      "G5-SUPPORT-02",
      "G5-SUPPORT-03",
      "G5-SUPPORT-04"
    ]
  },
  {
    "id": "T17",
    "name": "نوار باغ در امروز -> باغ -> جای‌گذاری/جابه‌جایی/بازگشت به انبار",
    "main": [
      "G5-BRIDGE-01",
      "G5-BRIDGE-31",
      "G5-BRIDGE-33",
      "G5-BRIDGE-34",
      "G5-BRIDGE-35"
    ]
  },
  {
    "id": "T18",
    "name": "مسیر مراقبتی: پیشنهاد -> شروع -> چک-این -> تکمیل -> خاطره -> جایزه باغ",
    "main": [
      "G5-JOURNEY-03",
      "G5-JOURNEY-05",
      "G5-JOURNEY-06",
      "G5-JOURNEY-07",
      "G5-JOURNEY-08",
      "G5-JOURNEY-09",
      "G5-JOURNEY-10",
      "G5-JOURNEY-11",
      "G5-JOURNEY-12",
      "G5-JOURNEY-18",
      "G5-JOURNEY-19",
      "G5-JOURNEY-20"
    ]
  }
];
  window.GATE52C_CAPABILITY_RECONCILIATION = [
  {
    "capability": "Household/pet bootstrap + pet list",
    "op": "GET /api/v1/me/context - GET /api/v1/pet-life/households/{household_id}/pets",
    "mappedScreens": [
      "G5-ONB-06",
      "G5-BRIDGE-02",
      "G5-ACC-02",
      "G5-ONB-09"
    ],
    "status": "endpoint-backed"
  },
  {
    "capability": "Order-line pet planning",
    "op": "PUT /api/v1/orders/{order_id}/pet-plan",
    "mappedScreens": [
      "G5-ORD-05"
    ],
    "status": "endpoint-backed"
  },
  {
    "capability": "Availability subscriptions",
    "op": "POST/DELETE /api/v1/catalog/offers/{offer_id}/availability-subscriptions - GET /api/v1/me/availability-subscriptions",
    "mappedScreens": [
      "G5-SHOP-06",
      "G5-SHOP-15",
      "G5-SHOP-16",
      "G5-SHOP-17",
      "G5-SHOP-18"
    ],
    "status": "endpoint-backed, order_created=false always"
  },
  {
    "capability": "Reorder assessment + snooze",
    "op": "POST /api/v1/pet-life/inventory/{unit_id}/reorder-assessment - PUT /api/v1/pet-life/inventory/{unit_id}/reorder-snooze",
    "mappedScreens": [
      "G5-BRIDGE-25",
      "G5-BRIDGE-26",
      "G5-BRIDGE-27",
      "G5-BRIDGE-28",
      "G5-BRIDGE-29",
      "G5-BRIDGE-30"
    ],
    "status": "endpoint-backed"
  },
  {
    "capability": "Support/concierge requests",
    "op": "POST /api/v1/customer-requests - GET /api/v1/customer-requests · GET /api/v1/customer-requests/{request_id}",
    "mappedScreens": [
      "G5-SUPPORT-01",
      "G5-SUPPORT-02",
      "G5-SUPPORT-03",
      "G5-SUPPORT-04"
    ],
    "status": "endpoint-backed"
  },
  {
    "capability": "Journey discovery/detail/check-ins",
    "op": "/api/v1/pet-life/* journey endpoints",
    "mappedScreens": [],
    "status": "enabled when runtime policy care_journey_delivery_enabled=true; enforce approved, active, species-eligible and professionally referenced journey content",
    "mappedScreens": ["G5-JOURNEY-01", "G5-JOURNEY-02", "G5-JOURNEY-03", "G5-JOURNEY-04", "G5-JOURNEY-05", "G5-JOURNEY-06", "G5-JOURNEY-07", "G5-JOURNEY-08", "G5-JOURNEY-09", "G5-JOURNEY-10", "G5-JOURNEY-11", "G5-JOURNEY-12", "G5-JOURNEY-13", "G5-JOURNEY-14", "G5-JOURNEY-15", "G5-JOURNEY-16", "G5-JOURNEY-17", "G5-JOURNEY-18", "G5-JOURNEY-19", "G5-JOURNEY-20"]
  },
  {
    "capability": "Garden return-to-storage",
    "op": "DELETE /api/v1/pet-life/garden/{reward_id}/placement",
    "mappedScreens": [
      "G5-BRIDGE-31",
      "G5-BRIDGE-32",
      "G5-BRIDGE-33",
      "G5-BRIDGE-34",
      "G5-BRIDGE-35"
    ],
    "status": "endpoint-backed"
  },
  {
    "capability": "Original/revised delivery commitments",
    "op": "GET /api/v1/orders/{order_id}/journey timeline + POST /api/v1/orders/{order_id}/delay-acknowledgements",
    "mappedScreens": [
      "G5-ORD-11"
    ],
    "status": "endpoint-backed"
  }
];
  window.GATE52C_RESIDUAL = [
  {
    "n": 1,
    "title": "Uncertain payment",
    "detail": "No customer reconciliation endpoint. Calm pending-verification state; never routes directly to retry."
  },
  {
    "n": 2,
    "title": "Semantic remaining level",
    "detail": "Server-owned bounds only. Client never converts level to grams."
  },
  {
    "n": 3,
    "title": "Quiet-hours read-back",
    "detail": "No GET exists in checked K9 openapi.json. Launch-hidden/deferred."
  }
];
  window.GATE52C_POLICY = {
  "currency_code": "IRR",
  "customer_display_currency_code": "IRR",
  "customer_display_unit": "TOMAN",
  "irr_per_customer_display_unit": 10,
  "delivery_commitment_hours": 366,
  "late_credit_enabled": false,
  "late_credit_customer_visible": false,
  "late_credit_basis_points": 500,
  "late_credit_expiry_months": 3,
  "wallet_consumption_order": "earliest_expiry_first",
  "full_payment_only": true,
  "reserve_now_enabled": false,
  "cancel_after_sourcing_enabled": false,
  "refund_self_service_enabled": false,
  "replacement_self_service_enabled": false,
  "substitution_self_service_enabled": false,
  "delay_compensation_customer_visible": false,
  "availability_subscriptions_enabled": true,
  "concierge_requests_enabled": true,
  "care_journey_delivery_enabled": true,
  "push_notifications_enabled": false,
  "semantic_level_estimation_enabled": true,
  "reorder_safety_buffer_days": 3,
  "reorder_snooze_early_break_worsening_days": 2,
  "customer_request_acknowledgement_fa": "درخواست شما ثبت شد. نتیجه بررسی از طریق پیامک یا داخل برنامه اطلاع‌رسانی می‌شود. ثبت درخواست به‌معنای تضمین موجودی، قیمت، زمان پاسخ یا تأمین نیست.",
  "storage_backend": "filesystem",
  "sourcing_start_rule": "supplier_financial_commitment_with_timestamp_and_evidence"
};
})();
