window.GATE2 = {
flows: [
{id:"A", title:"Commerce to activation", intent:"Buying never requires a pet. The pet profile is invited from real order data and skippable forever. A paid order is incoming inventory — never current food: no remaining-days math exists until delivery, assignment and a confirmed opening (Flow C).", reqs:["no profile needed to shop","skippable profile","planned assignment optional","incoming ≠ consuming","estimate starts at confirmed opening","existing-pet path"], frames:[
 {label:"A1 · PRODUCT — VISITOR", note:"Browsing and checkout never require a pet profile.", blocks:[{k:"title",t:"غذای خشک گربه — سالمون ۲ کیلو"},{k:"card",t:"۲٬۴۸۰٬۰۰۰ تومان",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز"},{k:"btn",t:"افزودن به سبد"},{k:"text",t:"بدون نیاز به حساب یا پروفایل حیوان"}]},
 {label:"A2 · ORDER PLACED — PLANNED ASSIGNMENT", note:"Pre-delivery assignment is a plan, not consumption: the product is «در راه», tracked in سفر سفارش (Flow S) — no remaining-days math yet.", blocks:[{k:"title",t:"سفارش ثبت شد ✓"},{k:"card",t:"سفر سفارش — پرداخت تأیید شد",sub:"در حال تأمین · تحویل وعده‌شده ۷ تا ۱۲ روز"},{k:"text",t:"این غذا برای کیست؟ (برنامه‌ریزی اختیاری)"},{k:"pills",opts:["یک حیوان","چند حیوان","فعلاً هیچ‌کدام"]}]},
 {label:"A3 · PROFILE — STEP 1 OF 3", note:"Skippable at every step; the order is unaffected.", blocks:[{k:"badge",t:"قدم ۱ از ۳"},{k:"input",t:"نام حیوان"},{k:"pills",opts:["گربه","سگ"]},{k:"btn",t:"ادامه"},{k:"ghost",t:"بعداً"}]},
 {label:"A4 · PROFILE — STEPS 2–3", note:"Incoming food pre-filled from the order — it becomes «غذای فعلی» only after delivery and a confirmed opening.", blocks:[{k:"badge",t:"قدم ۲ و ۳"},{k:"pills",opts:["بچه","بالغ","مسن"]},{k:"input",t:"وزن تقریبی (اختیاری)"},{k:"card",t:"غذای در راه: سالمون ۲ کیلو",sub:"پس از تحویل و باز شدن، غذای فعلی می‌شود"}]},
 {label:"A5 · ACTIVATION THRESHOLD", note:"'Activated' = species + age band + a linked food (incoming or assigned). Today may become home before the bag opens — but the food module shows an incoming/setup state, never a consumption estimate.", blocks:[{k:"title",t:"خانهٔ «امروزِ پیشی» آماده شد"},{k:"card",t:"غذای در راه: سالمون ۲ کیلو",sub:"سفر سفارش: در حال تأمین — تخمینِ روزها بعد از باز شدن کیسه"},{k:"btn",t:"برو به امروزِ پیشی"}]},
 {label:"A6 · BUYER ALREADY HAS PETS", note:"Existing owners skip profile creation; only assignment is asked. Their default home is already Today.", blocks:[{k:"title",t:"این سفارش برای کدام حیوان؟"},{k:"pills",opts:["پیشی","رکس","مشترک","هیچ‌کدام"]},{k:"text",t:"خانهٔ پیش‌فرض از قبل «امروز» است"}]},
 {label:"A7 · TODAY — BEFORE DELIVERY", note:"The activated home with an incoming bag: identity → incoming-food status → next event → compact garden. No days-remaining anywhere until the bag is opened.", blocks:[{k:"pets",t:"پیشی",sub:"+"},{k:"card",t:"سالمون ۲ کیلو — در راه",sub:"سفر سفارش: در حال تأمین · تحویل ۷ تا ۱۲ روز"},{k:"text",t:"تخمین روزها پس از باز شدن کیسه شروع می‌شود"},{k:"garden",t:"🌿 باغِ پیشی — زمین و نقشه"}]}
]},
{id:"B", title:"Returning owner — the 20-second visit", intent:"Open → understand → optionally act → leave. Fixed viewport order: ① identity & switching ② food status / most important current need ③ next relevant event ④ compact garden preview — present, never leading. No feeding registration in the default state: it appears only when an active journey requires it, an estimate needs meaningful correction, or the owner explicitly enabled regular logging. An empty day is read-only and calm.", reqs:["identity first","food status second","next event third","garden preview last · ≤ 96px","no default feeding log","empty day = read-only"], frames:[
 {label:"B1 · TODAY — FIRST VIEWPORT", note:"Fixed order: identity & switching → food status → next relevant event → compact garden strip (≤ 96px, last). No «ثبت غذای امروز» in the default state.", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"meter",t:"~۱۱روز",sub:"غذای خشک · تخمینی ۹ تا ۱۳ روز"},{k:"card",t:"امشب: چک‌این مسیر تغییر غذا",sub:"روز ۶ از ۱۴ — تنها درخواست امروز"},{k:"garden",t:"🌿 باغِ پیشی — آب روان است"}]},
 {label:"B2 · JOURNEY CHECK-IN DONE", note:"Feeding-related registration exists only because the active journey asked for it tonight (or via correction / explicit opt-in).", blocks:[{k:"card",t:"چک‌این امشب ثبت شد ✓",sub:"چون مسیر تغییر غذا فعال است"},{k:"text",t:"بازدید ~۲۰ ثانیه — می‌توانی بروی"}]},
 {label:"B3 · NOTHING NEEDED — READ-ONLY", note:"An empty day is read-only and calm: nothing to log, nothing to tap, no manufactured tasks.", blocks:[{k:"meter",t:"~۲۴روز",sub:"همه‌چیز روبه‌راه است"},{k:"text",t:"امروز هیچ کاری لازم نیست — چیزی برای ثبت هم نیست"},{k:"garden",t:"🌿 پیشی کنار حوض خوابیده"}]},
 {label:"B4 · SYSTEM / DATA ERROR", note:"Graceful degradation: one failing module never blanks Today.", blocks:[{k:"warn",t:"غذاسنج فعلاً در دسترس نیست — دوباره تلاش می‌کنیم"},{k:"card",t:"دفترچه و باغ در دسترس‌اند",sub:"بقیهٔ خانه کار می‌کند"}]}
]},
{id:"C", title:"Food-meter setup & correction", intent:"The estimate starts only at a confirmed opening — never on the delivery date. Shares and mix ratios are owner-provided or explicitly approximate; «نمی‌دانم» is a first-class answer that widens the band or falls back to a household-level estimate. A heuristic is never dressed up as precision.", reqs:["bag not opened","partly used","owner-stated shares","household-level fallback","mixed — owner ratio","«نمی‌دانم» supported","clearly wrong","external purchase"], frames:[
 {label:"C1 · ASSIGN FROM INVENTORY", note:"The household owns the bag; pets receive consumption assignments. External purchases enter the same inventory («افزودن غذای دیگر»).", blocks:[{k:"title",t:"کیسهٔ سالمون ۲ کیلو رسید"},{k:"pills",opts:["فقط پیشی","پیشی + رکس","بعداً"]},{k:"text",t:"خرید از جای دیگر؟ «افزودن غذای دیگر»"}]},
 {label:"C2 · OPEN DATE", note:"Unopened bags sit in inventory without consuming.", blocks:[{k:"title",t:"کیسه کی باز شد؟"},{k:"pills",opts:["هنوز باز نشده","امروز","چند روز پیش"]}]},
 {label:"C3 · PARTLY USED", note:"Visual quarter scale — the same control later serves as the correction UI.", blocks:[{k:"title",t:"حدوداً چقدر مانده؟"},{k:"pills",opts:["پر","بیش از نصف","کمتر از نصف","ته کیسه"]}]},
 {label:"C4 · PORTION UNKNOWN", note:"⚠ INTERNAL: guide values here are non-production sample copy. In production the guide card renders only if professionally approved — otherwise the module asks the owner or runs in bag-% mode. «نمی‌دانم» → wider band.", blocks:[{k:"title",t:"روزی حدوداً چقدر می‌خورد؟"},{k:"pills",opts:["خودم می‌گویم","نمی‌دانم"]},{k:"card",t:"راهنمای محصول: ~۵۵ گرم در روز",sub:"فقط در صورت تأیید متخصص نمایش داده می‌شود"}]},
 {label:"C5 · SHARED BAG — OWNER SHARES", note:"No automatic weight-based split. Shares are owner-provided or approximate; unknown → shared household-level estimate with a wider band.", blocks:[{k:"title",t:"پیشی و رکس از یک کیسه — سهم‌ها؟"},{k:"pills",opts:["سهم هر کدام را می‌گویم","حدودی: پیشی کمتر، رکس بیشتر","نمی‌دانم"]},{k:"text",t:"«نمی‌دانم» = تخمین مشترک در سطح خانه + بازهٔ پهن‌تر"}]},
 {label:"C6 · MIXED FEEDING — OWNER RATIO", note:"No fixed two-thirds assumption: the dry share comes from the owner, or stays unknown with a wider band.", blocks:[{k:"title",t:"فقط خشک یا ترکیبی؟"},{k:"pills",opts:["فقط خشک","بیشتر خشک","نصف‌نصف","بیشتر تر","نمی‌دانم"]},{k:"text",t:"سهم خشک را خودت مشخص می‌کنی — پیش‌فرضی در کار نیست"}]},
 {label:"C7 · RESULT + CONFIDENCE BAND", note:"A band, not a number. Low confidence = wider band + a gentle check question at a natural moment.", blocks:[{k:"meter",t:"~۶۰٪",sub:"۹ تا ۱۳ روز · تخمینی"},{k:"text",t:"هرچه از آخرین تأییدت بگذرد، بازه پهن‌تر می‌شود"},{k:"ghost",t:"اصلاح تخمین"}]},
 {label:"C8 · CLEARLY WRONG", note:"Recalibration uses bag openings, owner corrections, remaining-amount confirmations and journey data — reorders alone are never proof of consumption.", blocks:[{k:"warn",t:"به‌نظرت درست نیست؟"},{k:"pills",opts:["پر","بیش از نصف","کمتر از نصف","ته کیسه"]},{k:"text",t:"بازتنظیم فوری — و نرخ مصرف پیشی یاد گرفته می‌شود"}]}
]},
{id:"D", title:"Reorder preparation", intent:"Trigger = pessimistic remaining estimate vs. this offer's latest promised delivery + safety buffer. The explanation is outcome-first: the customer consequence leads, ranges and recommended action follow, and the arithmetic sits behind an optional «چطور محاسبه شد؟» disclosure. Dismissal, external purchase, unavailability and post-purchase delay are first-class paths.", reqs:["outcome first","math behind disclosure","offer-specific promise","snooze","bought elsewhere","unavailable","delayed after purchase"], frames:[
 {label:"D1 · REORDER CARD IN TODAY", note:"Promise is product/offer-specific — never a universal 10–14 days. One card max.", blocks:[{k:"card",t:"حدود ۱۸ روز غذا مانده",sub:"تأمین این محصول ۷ تا ۱۲ روز + ۵ روز اطمینان"},{k:"btn",t:"دیدن گزینه‌ها"},{k:"ghost",t:"بعداً (تا ۳ روز)"}]},
 {label:"D2 · WHY NOW — OUTCOME FIRST", note:"The customer consequence leads; then remaining range, promised range, buffer and recommended action. The formula is an optional disclosure (D2b).", blocks:[{k:"title",t:"چرا الان؟"},{k:"warn",t:"در سناریوی کندتر، غذا ممکن است پیش از رسیدن کیسهٔ جدید تمام شود"},{k:"card",t:"غذای باقی‌مانده: ~۱۶ تا ۲۱ روز",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز + ۵ روز اطمینان"},{k:"btn",t:"سفارش در همین هفته — پیشنهاد ما"},{k:"ghost",t:"چطور محاسبه شد؟"}]},
 {label:"D2b · HOW CALCULATED — OPTIONAL", note:"The arithmetic, only on request — never the lead.", blocks:[{k:"title",t:"چطور محاسبه شد؟"},{k:"text",t:"بدبینانه‌ترین تخمینِ غذا: ۱۶ روز"},{k:"text",t:"دیرترین تحویل وعده‌شده: ۱۲ روز"},{k:"text",t:"حاشیهٔ اطمینان: ۵ روز"},{k:"card",t:"۱۶ − (۱۲ + ۵) کمتر از صفر است",sub:"پس پیشنهاد: سفارش در همین هفته"}]},
 {label:"D3 · OPTIONS", note:"Every recommendation states its reason; prices and promises explicit. «هم‌ردهٔ تغذیه‌ای» claims may appear only with professional approval — until then the stated reason is availability/speed.", blocks:[{k:"card",t:"همان سالمون ۲ کیلو — ۲٬۴۸۰٬۰۰۰",sub:"تحویل ۷ تا ۱۲ روز"},{k:"card",t:"جایگزین: بوقلمون ۲ کیلو",sub:"تحویل ۵ تا ۹ روز · دلیل: تحویل سریع‌تر"},{k:"ghost",t:"جای دیگری خریدم"}]},
 {label:"D4 · BOUGHT ELSEWHERE", note:"External bags are first-class inventory; no sulking, no lost meter.", blocks:[{k:"title",t:"خریدی؟ خوب است"},{k:"pills",opts:["افزودن به انبار خانه"]},{k:"text",t:"غذاسنج با همان کیسه ادامه می‌دهد"}]},
 {label:"D5 · PRODUCT UNAVAILABLE", note:"Reserve language reuses the approved commerce pattern — explicit dates and prices.", blocks:[{k:"warn",t:"این محصول فعلاً موجود نیست"},{k:"card",t:"رزرو — تحویل ۱۰ تا ۱۶ روز",sub:"با تاریخ و قیمت صریح"},{k:"card",t:"جایگزین موجود",sub:"تحویل ۵ تا ۹ روز"}]},
 {label:"D6 · DELAYED AFTER PURCHASE", note:"The safety buffer absorbs the delay; if it can't, escalate honestly — no invented fixes.", blocks:[{k:"warn",t:"تحویل ۴ روز عقب افتاد — پوزش"},{k:"text",t:"غذا: ~۹ روز · تحویل جدید: ~۸ روز — چون زود سفارش دادی هنوز به‌موقع است"},{k:"ghost",t:"گفت‌وگو با پشتیبانی"}]},
 {label:"D7 · ARRIVAL → INVENTORY → ASSIGN", note:"The loop closes back into Flow C setup.", blocks:[{k:"title",t:"رسید ✓"},{k:"card",t:"انبار خانه: کیسهٔ جدید",sub:"نگشوده"},{k:"pills",opts:["انتساب به پیشی","بعداً"]},{k:"text",t:"پیگیری در «سفر سفارش» بسته شد"}]}
]},
{id:"E", title:"Food-transition journey", intent:"Offered, never auto-started — and offered only when its content is professionally approved. Unapproved content is not a customer state: the journey is hidden or disabled with no ratios, no Start and no symptom guidance («در انتظار تأیید» is internal-only wording). Exceptions never produce medical conclusions; stopping is respected; preference saved only with explicit confirmation.", reqs:["never auto-start","approved content only","unapproved → hidden","pause / adjust / stop","no medical conclusions","confirmed preference only"], frames:[
 {label:"E1 · ELIGIBILITY", note:"The journey is offered when blending is actually possible — never auto-started.", blocks:[{k:"card",t:"غذای جدید رسیده + ~۸ روز غذای قبلی",sub:"شرط ترکیب برقرار است"},{k:"btn",t:"بررسی مسیر تغییر غذا"},{k:"text",t:"هرگز خودکار شروع نمی‌شود"}]},
 {label:"E2 · PLAN REVIEW — APPROVED PLAN ONLY", note:"⚠ INTERNAL: ratios here are non-production sample copy. In production this screen exists only for professionally approved plans — no pending badge is ever shown to customers.", blocks:[{k:"text",t:"روز ۱–۴: ۷۵٪ قدیمی · روز ۵–۹: نصف‌نصف · روز ۱۰–۱۴: جدید"},{k:"card",t:"چون ~۸ روز غذای قدیمی داری",sub:"برنامه بر همان اساس تنظیم شده"},{k:"btn",t:"شروع"},{k:"ghost",t:"نه حالا"}]},
 {label:"E2b · CONTENT NOT APPROVED — INTERNAL STATE", note:"⚠ INTERNAL: when content is unapproved the owner simply never sees the journey — no ratios, no Start, no «در انتظار تأیید» message. The customer-facing design is absence.", blocks:[{k:"card",t:"امروزِ پیشی — بدون کارت مسیر",sub:"مسیر تغییر غذا پیشنهاد نمی‌شود"},{k:"text",t:"محتوای تأییدنشده اصلاً دیده نمی‌شود"}]},
 {label:"E3 · CHECK-IN", note:"Check-ins exist only inside the journey window — not a permanent daily ask.", blocks:[{k:"title",t:"امشب چطور بود؟"},{k:"pills",opts:["خوب خورد","کمتر خورد","مشکلی بود"]},{k:"text",t:"فقط در طول مسیر — نه همیشه"}]},
 {label:"E4 · EXCEPTION", note:"No diagnosis; always reversible. ⚠ INTERNAL: escalation wording is non-production sample copy — ships only after professional approval.", blocks:[{k:"warn",t:"باشد — یک قدم آرام‌تر می‌رویم"},{k:"text",t:"این تشخیص نیست؛ اگر تا ۲ روز ادامه داشت، با دامپزشک مشورت کن"},{k:"pills",opts:["ادامهٔ آهسته","مکث","توقف کامل"]}]},
 {label:"E5 · PAUSE / STOP", note:"Stopping is a safe, respected outcome — never framed as failure.", blocks:[{k:"title",t:"مسیر متوقف شد"},{k:"text",t:"تاریخچه در دفترچه می‌ماند؛ هر وقت خواستی، دوباره"},{k:"ghost",t:"شروع دوباره"}]},
 {label:"E6 · COMPLETION", note:"Preference saved only after explicit confirmation.", blocks:[{k:"title",t:"مسیر کامل شد ✓"},{k:"garden",t:"🌿 سروِ باغ آمادهٔ کاشت است"},{k:"card",t:"بوقلمون به ترجیح‌های پیشی اضافه شود؟",sub:"فقط با تأیید تو"},{k:"pills",opts:["بله","نه"]}]},
 {label:"E7 · DIARY MILESTONE", note:"Milestone = durable record, linked to the garden object.", blocks:[{k:"card",t:"دفترچه · آبان",sub:"تغییر غذا به بوقلمون — ۱۶ روز، با یک مکث"},{k:"text",t:"این خاطره به سروِ باغ پیوند خورد"}]}
]},
{id:"F", title:"Persian Garden V1", intent:"Preview → eligibility-based milestone → reveal → owner placement → memory → next meaningful slot. Unlocks come from a visible milestone catalogue — pets without a food-transition journey have alternative paths. Alive during inactivity — no deterioration, no stopped water, no recovery task; return triggers a warm greeting only.", reqs:["first visit","first reward","placement agency","returning visit","several objects","two pets","after inactivity (alive)","nearly full V1"], frames:[
 {label:"F1 · FIRST VISIT", note:"Exactly one dashed next-slot, always.", blocks:[{k:"garden",t:"🌿 زمین + نقشهٔ کم‌رنگ چهارباغ + پیشی"},{k:"text",t:"این باغ با رسیدگیِ واقعی ساخته می‌شود"},{k:"card",t:"جای خالی بعدی: سنگفرش",sub:"با تکمیل پروفایل"}]},
 {label:"F2 · FIRST REWARD", note:"Immediate feedback is subtle — a brief sprout glow, no confetti.", blocks:[{k:"title",t:"سنگفرشِ مسیر آماده شد"},{k:"garden",t:"🌿 جوانهٔ کوتاه — بازخورد لحظه‌ای، بی‌هیاهو"},{k:"btn",t:"کاشت در باغ"}]},
 {label:"F3 · PLACEMENT", note:"Owner agency: move anytime; removal → انبارک storage, never destroyed.", blocks:[{k:"title",t:"کجا بنشیند؟"},{k:"pills",opts:["قطعهٔ شمالی","کنار حوض","گوشهٔ نهال‌ها"]},{k:"text",t:"بعداً هم می‌توانی جابه‌جا کنی"}]},
 {label:"F4 · RETURNING VISIT", note:"The garden always answers: what grows next, and why.", blocks:[{k:"garden",t:"🌿 پیشی کنار حوض · آب روان"},{k:"card",t:"جای خالی بعدی: سرو",sub:"پایان مسیر تغییر غذا — یا مسیر جایگزین از کاتالوگ"}]},
 {label:"F5 · OBJECT → MEMORY", note:"Every object opens its diary memory.", blocks:[{k:"garden",t:"🌿 ضربه روی سرو…"},{k:"card",t:"این سرو",sub:"پایان مسیر تغییر غذا · آبان ۱۴۰۵ — دیدن در دفترچه"}]},
 {label:"F6 · TWO PETS, TWO GARDENS", note:"Independent gardens; palette varies by species; no comparison UI.", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"garden",t:"🌿 باغِ پیشی — سبز، حوضِ روان"},{k:"garden",t:"🌿 باغِ رکس — خاکِ گرم‌تر، تازه شروع"}]},
 {label:"F7 · AFTER 3 WEEKS AWAY", note:"Per the Gate 2 correction: no deterioration, no stopped water, no lost object, no recovery requirement. Return may trigger a warm greeting only.", blocks:[{k:"garden",t:"🌿 همان باغ — آب همچنان روان"},{k:"title",t:"خوش برگشتی — باغ منتظرت بود"},{k:"text",t:"هیچ چیزی کم نشده و هیچ جبرانی لازم نیست"}]},
 {label:"F8 · V1 NEARLY FULL (~DAY 90)", note:"V1 scope ends here; further quadrants are Next.", blocks:[{k:"garden",t:"🌿 قطعهٔ اول: کامل"},{k:"card",t:"قطعهٔ دومِ چهارباغ باز شد",sub:"+ کارت خاطرهٔ «فصل اول»"}]}
]},
{id:"G", title:"Pet switching & shared inventory", intent:"Switching swaps the entire pet layer; the household layer (inventory, orders, wallet) persists visibly. Bags belong to the household; consumption belongs to pets.", reqs:["active pet obvious","household bag ownership","co-consumers explicit","records & garden per pet","future member attribution"], frames:[
 {label:"G1 · TODAY — پیشی", note:"Shared-bag chip names co-consumers explicitly.", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"meter",t:"~۶۰٪",sub:"کیسهٔ مشترک با رکس — سهم پیشی"},{k:"card",t:"انبار خانه",sub:"۱ کیسهٔ باز (مشترک) · ۱ نگشوده"}]},
 {label:"G2 · SWITCHED — رکس", note:"Pet layer swaps completely; the household layer persists.", blocks:[{k:"pets",t:"رکس",sub:"پیشی"},{k:"meter",t:"~۶۰٪",sub:"همان کیسهٔ مشترک — سهم رکس"},{k:"garden",t:"🌿 باغِ رکس — مستقل از باغِ پیشی"}]},
 {label:"G3 · HOUSEHOLD INVENTORY", note:"Unassigned purchases are legitimate; external food is first-class.", blocks:[{k:"title",t:"انبار خانه"},{k:"card",t:"سالمون ۲ کیلو — باز",sub:"مصرف: پیشی + رکس"},{k:"card",t:"بوقلمون ۲ کیلو — نگشوده",sub:"انتساب: پیشی"},{k:"card",t:"غذای خریداری‌شده از جای دیگر",sub:"بدون انتساب — فقط موجودی"}]},
 {label:"G4 · MEMBER ATTRIBUTION", note:"The event contract carries the member now, so Next-phase household collaboration needs no remodel.", blocks:[{k:"badge",t:"FUTURE — همکاری خانگی"},{k:"card",t:"سینا غذای شب را داد",sub:"دیروز · ۲۱:۳۰"},{k:"text",t:"هر رویداد نام عضو ثبت‌کننده را دارد"}]}
]},
{id:"S", title:"سفر سفارش — order journey (replaces Journey Caravan)", intent:"A deliberately plain, factual status flow, separate from the pet home — no mascots, no gamification (the Journey Caravan artifact is deprecated, superseded by Gate 1.1 + Gate 2). Delivery hands off to household inventory and Flow C; the incoming product never consumes.", reqs:["payment confirmed","sourcing","in transit","delay honesty","delivered → inventory","planned assignment optional","no gamification"], frames:[
 {label:"S1 · PAYMENT CONFIRMED", note:"Statuses are facts with dates. Planned pet assignment is optional and editable.", blocks:[{k:"title",t:"سفر سفارش"},{k:"card",t:"پرداخت تأیید شد ✓",sub:"سالمون ۲ کیلو · امروز ۱۴:۲۰"},{k:"text",t:"انتساب برنامه‌ریزی‌شده: پیشی (اختیاری)"}]},
 {label:"S2 · SOURCING", note:"Offer-specific promised range; nothing consumes yet.", blocks:[{k:"card",t:"در حال تأمین",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز"},{k:"text",t:"هنوز چیزی مصرف نمی‌شود — فقط وضعیت سفارش"}]},
 {label:"S3 · IN TRANSIT", note:"Approximate arrival window in plain words.", blocks:[{k:"card",t:"در مسیر",sub:"رسیدن تقریبی: سه‌شنبه تا پنجشنبه"}]},
 {label:"S4 · DELAYED — HONEST", note:"Delay = apology + new explicit window; the reorder safety buffer absorbs it (D6).", blocks:[{k:"warn",t:"تحویل ۴ روز عقب افتاد — پوزش"},{k:"card",t:"بازهٔ جدید: شنبه تا دوشنبه",sub:"با تاریخ صریح"}]},
 {label:"S5 · DELIVERED → INVENTORY", note:"Handoff: household inventory, unopened, no estimate — Flow C takes over.", blocks:[{k:"title",t:"تحویل شد ✓"},{k:"card",t:"به انبار خانه اضافه شد",sub:"نگشوده — بدون تخمین مصرف"},{k:"text",t:"ادامه در خانهٔ حیوان: انتساب، باز کردن، تخمین"}]}
]}
],
contracts: [
{name:"Pet switcher", fa:"جابه‌جایی حیوان", rows:[["Purpose","Always know whose data is shown; switch context in one tap"],["Eligibility","≥ 1 pet profile"],["Trigger","Persistent in Today header"],["Inputs","Household pet list, active pet id"],["Source","Owner-created profiles"],["Confidence","Known"],["Primary action","Tap chip → full pet-layer swap"],["Dismissal","n/a — persistent"],["Data written","Last-active pet"],["Next state","Today re-renders for the selected pet"],["Empty state","Single pet: chip only + «افزودن حیوان»"],["Error state","Pet fails to load → retry; household layer stays usable"],["Analytics","switch_count, multi-pet visit ratio"],["Guardrails","Never mixes pet data; no pressure to switch"]]},
{name:"Food meter", fa:"غذاسنج", rows:[["Purpose","Answer 'how much food is left' without daily logging"],["Eligibility","Active pet has an assigned food with a start estimate"],["Trigger","Always shown in Today when eligible"],["Inputs","Bag size, confirmed open date, owner-stated portion & shares (or «نمی‌دانم»), owner-stated mix ratio, corrections, transition ratio"],["Source","Order data + product guide (expert-approved) + owner corrections"],["Confidence","Estimated — band shown; widens with time since last confirmation"],["Primary action","Open detail; one-tap quarter-scale correction"],["Dismissal","Collapsible; correction always offered — never silently wrong"],["Data written","Recalibration from bag openings, corrections, remaining confirmations and journey data — never from reorders alone"],["Next state","Narrower band; may make reorder card eligible"],["Empty state","No food → setup entry; incoming order → «در راه» status card, never an estimate"],["Error state","Guide missing → ask portion, or bag-% only mode"],["Analytics","correction_rate, band_width, accuracy vs reorder cycles"],["Guardrails","Always labeled تخمینی; unknown inputs widen the band — heuristics never shown as precision; never implies dietary adequacy or health"]]},
{name:"Reorder card", fa:"سفارش مجدد", rows:[["Purpose","Prevent running out, given real fulfillment timing"],["Eligibility","Pessimistic estimate ≤ latest promised delivery + safety buffer"],["Trigger","Threshold crossing (event)"],["Inputs","Pessimistic remaining, offer-specific promised delivery range, buffer, price, availability"],["Source","Commerce backend promise per offer"],["Confidence","Remaining: estimated · promise: known"],["Primary action","View options → checkout"],["Dismissal","بعداً (3-day snooze) / «جای دیگری خریدم» → external-bag flow"],["Data written","Order, snooze, dismissal, external purchase"],["Next state","Ordered → tracking chip; dismissed → silent until new threshold"],["Empty state","n/a — event-born"],["Error state","Unavailable → reserve / alternative with explicit promises"],["Analytics","shown→ordered rate, snooze rate, ran-out incidents"],["Guardrails","Full price/date facts; max one card; outcome-first explanation, math behind «چطور محاسبه شد؟»; a reorder is never consumption evidence; no urgency theatrics"]]},
{name:"Next action", fa:"اقدام بعدی", rows:[["Purpose","One small, genuinely useful thing right now"],["Eligibility","An approved, profile-relevant action exists"],["Trigger","Daily selection or journey schedule"],["Inputs","Profile, active journey step, content library + approval status"],["Source","Expert-approved content only — unapproved content is hidden, never marked «pending» to customers"],["Confidence","Recommendation — labeled «پیشنهاد»"],["Primary action","Do it + one-tap ثبت"],["Dismissal","«امروز نه» — no penalty, no forced replacement"],["Data written","Completion event (→ diary); dismissal"],["Next state","Done state; garden progress if part of a milestone"],["Empty state","Hidden entirely — no filler"],["Error state","Content unavailable → hidden"],["Analytics","completion, dismissal; dismiss-streak → auto-reduce frequency"],["Guardrails","Never commerce disguised as care; optional forever; removable experiment"]]},
{name:"Active journey", fa:"مسیر فعال", rows:[["Purpose","Guide a finite real process (e.g. food transition) safely"],["Eligibility","Owner explicitly started a journey"],["Trigger","Journey schedule (check-in windows)"],["Inputs","Plan template (approval status), progress, exceptions"],["Source","Professionally approved content only + owner check-ins"],["Confidence","Plan: approved · progress: known"],["Primary action","Check-in; open journey page"],["Dismissal","Pause / adjust / stop — always available, keeps history"],["Data written","Check-ins, exceptions, plan adjustments, completion"],["Next state","Next check-in, adjusted plan, or completion → diary + garden"],["Empty state","No journey → card absent (B3)"],["Error state","Plan content unavailable → journey paused with honest notice"],["Analytics","adoption, completion, voluntary exit, exception frequency, usefulness rating"],["Guardrails","Never auto-starts; unapproved content → journey hidden/disabled (no ratios, no Start, no pending message); no medical conclusions"]]},
{name:"Weekly recap", fa:"مرور هفتگی", rows:[["Purpose","Friendly interpretation of the week; one suggested focus"],["Eligibility","Sufficient meaningful data exists (threshold with data team)"],["Trigger","Weekly, end of week"],["Inputs","Week's events, journey progress, new profile knowledge"],["Source","Recorded events + platform interpretation"],["Confidence","Interpretation — worded as observation, never judgment"],["Primary action","Read; optionally adopt the suggested focus"],["Dismissal","Close; archived into دفترچه"],["Data written","Read state, focus adoption; memory card"],["Next state","Card leaves Today; next recap next week"],["Empty state","Not generated — never a manufactured empty summary"],["Error state","Partial data → shorter recap, no fabrication"],["Analytics","open rate, focus adoption, guilt-language audit"],["Guardrails","No missed-day punishment; no health conclusions; no fabricated stats; reading never unlocks a Garden change — memory card only"]]},
{name:"Garden preview", fa:"نوار باغ", rows:[["Purpose","Compact emotional presence of the pet's garden in Today"],["Eligibility","Garden experiment enabled"],["Trigger","Always (when enabled); pulses subtly on new reward"],["Inputs","Garden state, pending reward, next slot"],["Source","Milestone engine"],["Confidence","Known"],["Primary action","Tap → full garden"],["Dismissal","Collapsible; product fully works with garden disabled"],["Data written","Open events"],["Next state","Full garden"],["Empty state","Day-0 plot with pet present — never blank"],["Error state","Render failure → strip hidden, Today unaffected"],["Analytics","open rate, downstream utility use after open"],["Guardrails","≤ 96px in first viewport; never pushes utility below fold; no health signal"]]},
{name:"Full garden", fa:"باغ کامل", rows:[["Purpose","Emotional progression space owned by the pet"],["Eligibility","From garden preview"],["Trigger","User action only"],["Inputs","Objects, placements, memories, next slot, pet presence, time of day"],["Source","Milestone engine + diary links"],["Confidence","Known"],["Primary action","Place/move objects; tap object → memory; view next slot reason"],["Dismissal","Back to Today"],["Data written","Placements, moves, storage (انبارک)"],["Next state","Updated garden; diary opens on memory tap"],["Empty state","Plot + plan + pet + one dashed slot"],["Error state","Asset missing → placeholder shape, no data loss"],["Analytics","placement rate, memory opens, return-visit correlation"],["Guardrails","No XP/levels/streaks; no decay; no purchased objects; no spend rewards; no repeated-tap rewards; no health interpretation"]]},
{name:"Diary", fa:"دفترچه", rows:[["Purpose","Durable pet history: actions, milestones, future records"],["Eligibility","Always (activated pet)"],["Trigger","User action; auto-entries from events"],["Inputs","Events, milestones, recaps, garden links, member attribution"],["Source","Owner actions + platform events (+ verified providers, future)"],["Confidence","Recorded facts; interpretations labeled"],["Primary action","Browse timeline; open memory"],["Dismissal","n/a — destination"],["Data written","Manual notes (optional)"],["Next state","—"],["Empty state","First-entry invitation: «اولین روزِ پیشی اینجا ثبت می‌شود»"],["Error state","Sync issue → read-only cache + notice"],["Analytics","revisit rate, memory opens from garden"],["Guardrails","Pet-owned data; travels with the pet (future transfer); no health scoring"]]},
{name:"Profile prompt", fa:"تکمیل تدریجی پروفایل", rows:[["Purpose","Enrich the profile gradually, at useful moments"],["Eligibility","Missing field that would improve an active module"],["Trigger","Contextual event (e.g. meter needs weight) — not a nag schedule"],["Inputs","Profile gaps, module needs"],["Source","Owner"],["Confidence","Known once answered"],["Primary action","Answer one small question"],["Dismissal","Skip — same question not re-asked for weeks"],["Data written","Profile field + provenance"],["Next state","Dependent module improves visibly («دقیق‌تر شد ✓»)"],["Empty state","Profile complete → prompt never appears"],["Error state","—"],["Analytics","answer rate, skip rate, downstream accuracy gain"],["Guardrails","One question at a time; always explains why it's asked; partial profile fully supported"]]}
],
gardenTimeline: [
{d:"روز ۰", obj:"زمین، نقشهٔ کم‌رنگ چهارباغ، حضور حیوان", src:"فعال‌سازی"},
{d:"روز ۱–۳", obj:"سنگفرش مسیر اول", src:"تکمیل پروفایل پایه"},
{d:"~هفتهٔ ۱", obj:"حوض (هنوز بی‌آب)", src:"راه‌اندازی کامل غذاسنج + اولین اصلاح"},
{d:"~روز ۱۰", obj:"آبِ روان", src:"ثبت اولین خاطرهٔ ماندگار در دفترچه"},
{d:"~روز ۲۱", obj:"بوته‌های گل", src:"هفتهٔ سرگرمی (آزمایشی)"},
{d:"~روز ۴۰", obj:"سرو", src:"پایان مسیر تغییر غذا"},
{d:"~روز ۵۵", obj:"پرچین و گلدان", src:"مسیر دوم یا نقطهٔ عطف تأییدشدهٔ صاحب (مثلاً سالگرد)"},
{d:"~روز ۷۵", obj:"درخت انار", src:"پایان یک برنامهٔ غنی‌سازی/سرگرمی"},
{d:"~روز ۹۰", obj:"قطعهٔ اول کامل → گشایش قطعهٔ دوم + کارت خاطرهٔ «فصل اول»", src:"جمعِ نقاط عطف"}
],
gardenRules: [
{t:"Milestone catalogue (eligibility-based)", d:"Meaningful journey completions · owner-confirmed pet milestones (birthday, adoption day, recorded firsts) · useful profile enrichment · completed enrichment programs · durable recorded memories. Never: purchases, Garden opens, recap reads, app visits, repeated taps, notification responses, hidden activity points."},
{t:"Example, not schedule", d:"The 90-day strip above is one illustrative example. Milestones unlock by eligibility whenever they actually happen — there is no fixed Day 0–90 program. Immediate feedback is a subtle sprout glow, reserved for real milestones."},
{t:"Recaps → memory only", d:"Reading or opening a weekly recap never unlocks a Garden change. It may create a diary memory card only."},
{t:"Paths without a transition journey", d:"Every slot has alternative eligibility: the cypress can also come from a completed enrichment program or an owner-confirmed milestone. No pet is locked out for skipping a food transition."},
{t:"Duplicates & repeated journeys", d:"A second completed transition adds a growth ring / blossom to the existing cypress + a diary entry — never a duplicate object. Repetition deepens, doesn't clutter."},
{t:"Placement, movement, removal", d:"New objects arrive in the نهال‌ها corner; the owner places them. Move anytime in edit mode. Removal → انبارک (storage) — objects are never destroyed or lost."},
{t:"Objects ↔ diary", d:"Every object is born from a diary milestone and links back to it. Tap object → memory card → full diary entry. The garden is the diary, rendered emotionally."},
{t:"Multi-pet", d:"One garden per pet, species-tinted palette, independent progress. Shared-bag milestones credit each pet's own relevant milestone once — no double-dipping, no comparison."},
{t:"Quadrant opening — explicit", d:"A quadrant opens when its visible milestone slots are filled — shown as «X از Y جای‌گاه»; the owner can always see which milestone opened what. No hidden XP or point totals. Existing objects untouched; V1 ships one quadrant + this unlock; further quadrants are Next."},
{t:"Hard rules", d:"No XP or owner levels · no daily streaks · no loss or decay · no purchased objects · no reward for spending, Garden opens, recap reads, app visits or notification responses · no health interpretation · product fully works with Garden disabled."}
],
experiments: [
{name:"Persian Garden V1", hyp:"Emotional progression tied to real care increases meaningful weekly return and milestone completion — not just garden opens.", measure:["Weekly return of activated owners (vs. garden-disabled cohort)","Journey & milestone completion","Memory revisits (diary opens from garden)","Continued use of useful modules after garden opens"], guard:["No reduction in shop/checkout completion","No increase in notification volume","Zero health-status confusion in research sessions"], removal:"If after 2 evaluation cycles garden engagement is decorative-only (opens without downstream utility or return effect) → demote to static illustration."},
{name:"Food-transition journey", hyp:"A guided, reversible plan makes transitions safer and more complete than a static article.", measure:["Qualified adoption (offered → started)","Completion rate","Voluntary exit (counted as a healthy outcome, tracked separately)","Exception frequency","Post-journey usefulness rating"], guard:["Expert sign-off before any ratio content leaves placeholder state","Escalation wording tested for clarity"], removal:"Low usefulness rating or recurring confusion → revert to expert-written static guide."},
{name:"Weekly recap", hyp:"A no-guilt weekly interpretation creates a reliable weekly return rhythm.", measure:["Open rate","Suggested-focus adoption","Recap-driven diary revisits"], guard:["Generated only when sufficient meaningful data exists — never a manufactured summary","Guilt-language audit on every template"], removal:"If opened without downstream value → merge into diary as a passive monthly digest."},
{name:"Daily suggestion", hyp:"One small optional daily action adds value without nagging.", measure:["Completion rate","Dismissal rate & dismiss-streaks (annoyance signal)"], guard:["Dismissible; auto-reduces frequency on dismiss-streaks","Hidden entirely when no approved relevant content exists"], removal:"If dismissal dominates completion after frequency auto-reduction → remove module."}
],
stateMap: [
{s:"New / empty", w:"A3–A5 · F1"},{s:"Incoming order (pre-delivery)", w:"A7 · Flow S"},{s:"Unapproved content (internal)", w:"E2b · journey contract"},{s:"Partial profile", w:"A4 · contract: profile prompt"},{s:"Active", w:"B1"},{s:"Low-confidence estimate", w:"C7"},{s:"Corrected estimate", w:"C8"},{s:"No current food", w:"contract: food meter — empty"},{s:"No journey", w:"B3"},{s:"Completed journey", w:"E6–E7"},{s:"Shared product", w:"C5 · G1–G3"},{s:"Product unavailable", w:"D5"},{s:"Delayed delivery", w:"D6"},{s:"Dismissed recommendation", w:"D1 · contract: reorder"},{s:"Returning after inactivity", w:"F7"},{s:"System / data error", w:"B4 · contract error rows"}
],
assumptions: [
{t:"Feeding-guide data per SKU", a:"Assumed available per product for the meter's base model.", o:"Ops / content — confirm coverage"},
{t:"Expert validation pipeline", a:"Unapproved content is never customer-facing — journeys hidden/disabled, guide cards absent. Boards mark sample copy as internal/non-production.", o:"Vet advisor — define workflow"},
{t:"Offer-specific delivery promise", a:"Commerce backend exposes a promised-delivery range per offer.", o:"Engineering — confirm API"},
{t:"Safety buffer size", a:"5 days used in examples; real value needs fulfillment variance data.", o:"Ops — decide"},
{t:"Share elicitation wording", a:"Auto weight-split removed (Gate 2.1): shares are owner-provided, approximate, or unknown → household-level estimate with wider bands. Wording for approximate shares needs testing.", o:"Research — test"},
{t:"سفر سفارش status set", a:"The review's status list arrived truncated; minimal set used: payment confirmed → sourcing → in transit → delivered → inventory. Confirm exact statuses.", o:"Product — confirm"},
{t:"Recap data threshold", a:"'Sufficient meaningful data' threshold intentionally undefined — no invented percentages.", o:"Data — define with real usage"},
{t:"Notification budget", a:"Event triggers assume a per-week cap; channel strategy undecided.", o:"Product — decide"},
{t:"Home naming", a:"«امروزِ [نام]» used as working title; final name deferred per brief.", o:"Brand — later"},
{t:"External bag matching", a:"MVP: manual product pick for outside purchases; barcode scan is Future.", o:"Engineering — scope"}
],
proto: {
A: [
 {label:"PRODUCT — VISITOR", blocks:[{k:"title",t:"غذای خشک گربه — سالمون ۲ کیلو"},{k:"card",t:"۲٬۴۸۰٬۰۰۰ تومان",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز"},{k:"text",t:"بدون نیاز به پروفایل حیوان"},{k:"btn",t:"خرید و پرداخت",tap:1}]},
 {label:"ORDER PLACED — INCOMING", blocks:[{k:"title",t:"سفارش ثبت شد ✓"},{k:"card",t:"سفر سفارش — پرداخت تأیید شد",sub:"در حال تأمین · تحویل ۷ تا ۱۲ روز"},{k:"text",t:"این غذا برای کیست؟ (برنامه‌ریزی اختیاری)"},{k:"pills",opts:[{t:"ساخت پروفایل پیشی",tap:2},{t:"فعلاً هیچ‌کدام",tap:10}]}]},
 {label:"PROFILE — STEP 1/3", blocks:[{k:"badge",t:"قدم ۱ از ۳"},{k:"input",t:"نام: پیشی"},{k:"text",t:"نوع حیوان؟"},{k:"pills",opts:[{t:"گربه",tap:3},{t:"سگ",tap:3}]}]},
 {label:"PROFILE — STEP 2/3", blocks:[{k:"badge",t:"قدم ۲ از ۳"},{k:"text",t:"سن تقریبی؟"},{k:"pills",opts:[{t:"بچه",tap:4},{t:"بالغ",tap:4},{t:"مسن",tap:4}]}]},
 {label:"PROFILE — STEP 3/3", blocks:[{k:"badge",t:"قدم ۳ از ۳"},{k:"card",t:"غذای در راه: سالمون ۲ کیلو",sub:"پس از تحویل و باز شدن، «غذای فعلی» می‌شود"},{k:"btn",t:"تأیید و فعال‌سازی",tap:5}]},
 {label:"TODAY — BEFORE DELIVERY (INCOMING)", blocks:[{k:"pets",t:"پیشی",sub:"+"},{k:"card",t:"سالمون ۲ کیلو — در راه",sub:"سفر سفارش: در حال تأمین · تحویل ۷ تا ۱۲ روز"},{k:"text",t:"تخمین روزها پس از باز شدن کیسه شروع می‌شود"},{k:"garden",t:"🌿 باغِ پیشی — زمین و نقشه"},{k:"btn",t:"شبیه‌سازی: تحویل شد",tap:6}]},
 {label:"DELIVERED → HOUSEHOLD INVENTORY", blocks:[{k:"title",t:"رسید ✓ — به انبار خانه اضافه شد"},{k:"card",t:"سالمون ۲ کیلو",sub:"نگشوده — بدون تخمین"},{k:"text",t:"انتساب مصرف؟"},{k:"pills",opts:[{t:"پیشی",tap:7},{t:"بعداً",tap:7}]}]},
 {label:"CONFIRM OPENING", blocks:[{k:"title",t:"کیسه باز شد؟"},{k:"pills",opts:[{t:"امروز باز شد",tap:8},{t:"هنوز نه",tap:6}]},{k:"text",t:"تا باز شدن، فقط «نگشوده» در انبار می‌ماند"}]},
 {label:"REMAINING + PORTION", blocks:[{k:"title",t:"چقدر مانده و روزی حدوداً چقدر؟"},{k:"pills",opts:[{t:"پر — سهم روزانه را می‌گویم",tap:9},{t:"پر — نمی‌دانم",tap:9}]},{k:"text",t:"«نمی‌دانم» = شروع با بازهٔ پهن‌تر"}]},
 {label:"ESTIMATE STARTED", blocks:[{k:"pets",t:"پیشی",sub:"+"},{k:"meter",t:"~۲۸روز",sub:"۲۲ تا ۳۴ روز · تخمینی — با «نمی‌دانم» بازه پهن‌تر است"},{k:"garden",t:"🌿 باغِ پیشی — زمین و نقشه"},{k:"ghost",t:"شروع دوباره",tap:0}]},
 {label:"SKIPPED — SHOP STAYS HOME", blocks:[{k:"title",t:"فروشگاه"},{k:"card",t:"برای گربه‌ات خانه‌ای بساز",sub:"هر وقت خواستی — از همین سفارش"},{k:"pills",opts:[{t:"ساخت پروفایل",tap:2},{t:"شروع دوباره",tap:0}]}]}
],
B: [
 {label:"TODAY — CORRECTED HIERARCHY", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"meter",t:"~۱۱روز",sub:"۹ تا ۱۳ روز · تخمینی"},{k:"card",t:"امشب: چک‌این مسیر تغییر غذا",sub:"روز ۶ از ۱۴ — تنها درخواست امروز"},{k:"garden",t:"🌿 باغِ پیشی — آب روان است"},{k:"btn",t:"جزئیات غذاسنج",tap:1},{k:"ghost",t:"روزِ خالی را ببین (شبیه‌سازی)",tap:2}]},
 {label:"METER DETAIL + CORRECTION", blocks:[{k:"meter",t:"~۶۰٪",sub:"۹ تا ۱۳ روز · تخمینی"},{k:"text",t:"مبنا: باز شدنِ کیسه + سهمِ گفتهٔ تو + اصلاح‌ها"},{k:"text",t:"به‌نظرت درست نیست؟"},{k:"pills",opts:[{t:"پر",tap:3},{t:"بیش از نصف",tap:3},{t:"کمتر از نصف",tap:3},{t:"ته کیسه",tap:3}]},{k:"ghost",t:"بازگشت",tap:0}]},
 {label:"EMPTY DAY — READ-ONLY", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"meter",t:"~۲۴روز",sub:"همه‌چیز روبه‌راه است"},{k:"text",t:"امروز هیچ کاری لازم نیست — چیزی برای ثبت هم نیست"},{k:"garden",t:"🌿 پیشی کنار حوض خوابیده"},{k:"ghost",t:"بازگشت",tap:0}]},
 {label:"CORRECTED", blocks:[{k:"card",t:"بازتنظیم شد ✓",sub:"تخمین جدید: ۸ تا ۱۰ روز"},{k:"text",t:"نرخ مصرف پیشی برای کیسه‌های بعدی یاد گرفته شد"},{k:"ghost",t:"بازگشت به امروز",tap:0}]}
],
D: [
 {label:"TODAY + REORDER CARD", blocks:[{k:"pets",t:"پیشی",sub:"رکس"},{k:"card",t:"حدود ۱۸ روز غذا مانده",sub:"تأمین این محصول ۷ تا ۱۲ روز + ۵ روز اطمینان"},{k:"btn",t:"چرا الان؟",tap:1},{k:"btn",t:"دیدن گزینه‌ها",tap:2},{k:"ghost",t:"بعداً (تا ۳ روز)",tap:5}]},
 {label:"WHY NOW — OUTCOME FIRST", blocks:[{k:"title",t:"چرا الان؟"},{k:"warn",t:"در سناریوی کندتر، غذا ممکن است پیش از رسیدن کیسهٔ جدید تمام شود"},{k:"card",t:"غذای باقی‌مانده: ~۱۶ تا ۲۱ روز",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز + ۵ روز اطمینان"},{k:"btn",t:"دیدن گزینه‌ها",tap:2},{k:"ghost",t:"چطور محاسبه شد؟",tap:7},{k:"ghost",t:"بازگشت",tap:0}]},
 {label:"OPTIONS", blocks:[{k:"card",t:"همان سالمون ۲ کیلو — ۲٬۴۸۰٬۰۰۰",sub:"تحویل ۷ تا ۱۲ روز"},{k:"btn",t:"سفارش همین",tap:3},{k:"card",t:"جایگزین: بوقلمون — تحویل ۵ تا ۹ روز",sub:"دلیل: تحویل سریع‌تر"},{k:"ghost",t:"جای دیگری خریدم",tap:4}]},
 {label:"ORDERED → INVENTORY", blocks:[{k:"title",t:"سفارش ثبت شد ✓"},{k:"card",t:"پیگیری در سفر سفارش",sub:"وعدهٔ تحویل: ۷ تا ۱۲ روز"},{k:"text",t:"وقتی برسد، به انبار خانه اضافه می‌شود"},{k:"pills",opts:[{t:"انتساب به پیشی",tap:6},{t:"بعداً",tap:6}]}]},
 {label:"BOUGHT ELSEWHERE", blocks:[{k:"title",t:"خریدی؟ خوب است"},{k:"text",t:"غذاسنج با همان کیسه ادامه می‌دهد"},{k:"pills",opts:[{t:"افزودن به انبار خانه",tap:6}]}]},
 {label:"SNOOZED", blocks:[{k:"card",t:"باشد — تا ۳ روز دیگر ساکت می‌مانیم",sub:"مگر تخمین بدتر شود"},{k:"ghost",t:"شروع دوباره",tap:0}]},
 {label:"INVENTORY UPDATED", blocks:[{k:"title",t:"انبار خانه"},{k:"card",t:"سالمون — باز",sub:"مصرف: پیشی"},{k:"card",t:"کیسهٔ جدید",sub:"نگشوده"},{k:"ghost",t:"شروع دوباره",tap:0}]},
 {label:"HOW CALCULATED — OPTIONAL", blocks:[{k:"title",t:"چطور محاسبه شد؟"},{k:"text",t:"بدبینانه‌ترین تخمین غذا: ۱۶ روز"},{k:"text",t:"دیرترین تحویل وعده‌شده: ۱۲ روز"},{k:"text",t:"حاشیهٔ اطمینان: ۵ روز"},{k:"card",t:"۱۶ − (۱۲ + ۵) کمتر از صفر",sub:"پس پیشنهاد: سفارش در همین هفته"},{k:"ghost",t:"بازگشت",tap:1}]}
],
E: [
 {label:"ELIGIBILITY", blocks:[{k:"card",t:"غذای جدید رسیده + ~۸ روز غذای قبلی",sub:"شرط ترکیب برقرار است"},{k:"text",t:"هرگز خودکار شروع نمی‌شود"},{k:"btn",t:"بررسی مسیر تغییر غذا",tap:1}]},
 {label:"PLAN REVIEW", blocks:[{k:"text",t:"روز ۱–۴: ۷۵٪ قدیمی · روز ۵–۹: نصف‌نصف · روز ۱۰–۱۴: جدید"},{k:"card",t:"چون ~۸ روز غذای قدیمی داری",sub:"برنامه بر همان اساس تنظیم شده"},{k:"btn",t:"شروع",tap:2},{k:"ghost",t:"نه حالا",tap:0}]},
 {label:"CHECK-IN — NIGHT 6", blocks:[{k:"title",t:"امشب چطور بود؟"},{k:"pills",opts:[{t:"خوب خورد",tap:4},{t:"کمتر خورد",tap:3},{t:"مشکلی بود",tap:3}]},{k:"text",t:"فقط در طول مسیر — نه همیشه"}]},
 {label:"EXCEPTION", blocks:[{k:"warn",t:"باشد — یک قدم آرام‌تر می‌رویم"},{k:"text",t:"این تشخیص نیست؛ اگر تا ۲ روز ادامه داشت، با دامپزشک مشورت کن"},{k:"pills",opts:[{t:"ادامهٔ آهسته",tap:2},{t:"مکث",tap:5},{t:"توقف کامل",tap:5}]}]},
 {label:"COMPLETION — DAY 14", blocks:[{k:"title",t:"مسیر کامل شد ✓"},{k:"garden",t:"🌿 سروِ باغ آمادهٔ کاشت است"},{k:"card",t:"بوقلمون به ترجیح‌های پیشی اضافه شود؟",sub:"فقط با تأیید تو"},{k:"pills",opts:[{t:"بله",tap:6},{t:"نه",tap:6}]}]},
 {label:"PAUSED / STOPPED", blocks:[{k:"title",t:"مسیر متوقف شد"},{k:"text",t:"تاریخچه در دفترچه می‌ماند؛ هر وقت خواستی، دوباره"},{k:"ghost",t:"شروع دوباره",tap:0}]},
 {label:"DIARY + GARDEN", blocks:[{k:"card",t:"دفترچه · آبان",sub:"تغییر غذا به بوقلمون — با یک مکث"},{k:"garden",t:"🌿 سرو کاشته شد — پیوند به همین خاطره"},{k:"ghost",t:"شروع دوباره",tap:0}]}
],
F: [
 {label:"FIRST VISIT", blocks:[{k:"garden",t:"🌿 زمین + نقشهٔ کم‌رنگ + پیشی"},{k:"text",t:"این باغ با رسیدگیِ واقعی ساخته می‌شود"},{k:"card",t:"جای خالی بعدی: سنگفرش",sub:"با تکمیل پروفایل"},{k:"btn",t:"تکمیل پروفایل (شبیه‌سازی)",tap:1}]},
 {label:"FIRST REWARD", blocks:[{k:"title",t:"سنگفرشِ مسیر آماده شد"},{k:"garden",t:"🌿 جوانهٔ کوتاه — بی‌هیاهو"},{k:"btn",t:"کاشت در باغ",tap:2}]},
 {label:"PLACEMENT", blocks:[{k:"title",t:"کجا بنشیند؟"},{k:"pills",opts:[{t:"قطعهٔ شمالی",tap:3},{t:"کنار حوض",tap:3},{t:"گوشهٔ نهال‌ها",tap:3}]},{k:"text",t:"بعداً هم می‌توانی جابه‌جا کنی"}]},
 {label:"PLACED — RETURNING VIEW", blocks:[{k:"garden",t:"🌿 سنگفرش نشسته · پیشی کنار آن"},{k:"card",t:"جای خالی بعدی: سرو",sub:"پایان مسیر تغییر غذا — یا مسیر جایگزین از کاتالوگ"},{k:"btn",t:"ضربه روی سنگفرش",tap:4},{k:"ghost",t:"جهش به روز ۹۰",tap:5}]},
 {label:"OBJECT → MEMORY", blocks:[{k:"card",t:"این سنگفرش",sub:"تکمیل پروفایل پیشی · مهر ۱۴۰۵"},{k:"text",t:"دیدن خاطرهٔ کامل در دفترچه"},{k:"ghost",t:"بازگشت به باغ",tap:3}]},
 {label:"~DAY 90 — QUADRANT FULL", blocks:[{k:"garden",t:"🌿 قطعهٔ اول: کامل — آب همچنان روان"},{k:"card",t:"قطعهٔ دومِ چهارباغ باز شد",sub:"+ کارت خاطرهٔ «فصل اول»"},{k:"ghost",t:"شروع دوباره",tap:0}]}
],
S: [
 {label:"PAYMENT CONFIRMED", blocks:[{k:"title",t:"سفر سفارش"},{k:"card",t:"پرداخت تأیید شد ✓",sub:"سالمون ۲ کیلو · امروز ۱۴:۲۰"},{k:"text",t:"انتساب برنامه‌ریزی‌شده: پیشی (اختیاری، قابل تغییر)"},{k:"btn",t:"مرحلهٔ بعد",tap:1}]},
 {label:"SOURCING", blocks:[{k:"card",t:"در حال تأمین",sub:"تحویل وعده‌شده: ۷ تا ۱۲ روز"},{k:"text",t:"هنوز چیزی مصرف نمی‌شود — فقط وضعیت سفارش"},{k:"btn",t:"مرحلهٔ بعد",tap:2}]},
 {label:"IN TRANSIT", blocks:[{k:"card",t:"در مسیر",sub:"رسیدن تقریبی: سه‌شنبه تا پنجشنبه"},{k:"btn",t:"تحویل شد",tap:3},{k:"ghost",t:"تأخیر (شبیه‌سازی)",tap:4}]},
 {label:"DELIVERED → INVENTORY", blocks:[{k:"title",t:"تحویل شد ✓"},{k:"card",t:"به انبار خانه اضافه شد",sub:"نگشوده — بدون تخمین مصرف"},{k:"text",t:"ادامه در خانهٔ حیوان: انتساب، باز کردن، تخمین"},{k:"ghost",t:"شروع دوباره",tap:0}]},
 {label:"DELAYED — HONEST", blocks:[{k:"warn",t:"تحویل ۴ روز عقب افتاد — پوزش"},{k:"card",t:"بازهٔ جدید: شنبه تا دوشنبه",sub:"با تاریخ صریح"},{k:"btn",t:"تحویل شد",tap:3}]}
]
}
};
